'use client';
import { InlineMath, BlockMath } from '@/components/math';
import { NotationBox, TryIt } from '@/components/lesson';

export default function Lesson17Content() {
  return (
    <>
      <NotationBox>
        <NotationBox.Item heading="Universality">
          <NotationBox.Text>
            A gate set is <strong>universal</strong> if every unitary can be approximated to any accuracy <InlineMath math="\varepsilon" /> by a finite sequence of its gates:
          </NotationBox.Text>
          <NotationBox.Formula math="\|U - G_m\cdots G_2G_1\| \le \varepsilon" note="Approximation is unavoidable: a finite gate set produces only countably many circuits." />
        </NotationBox.Item>
        <NotationBox.Item heading="Key terms">
          <NotationBox.List items={[
            { term: 'Clifford gates', description: <>Generated by <InlineMath math="H" />, <InlineMath math="S" />, and CNOT. They map Pauli operators to Pauli operators.</> },
            { term: 'T gate', description: <><InlineMath math="T = \mathrm{diag}(1, e^{i\pi/4})" />, with <InlineMath math="T^2 = S" />. It is not Clifford.</> },
            { term: 'T-count', description: 'The number of T gates in a circuit, the main cost measure in fault-tolerant computing.' },
          ]} />
        </NotationBox.Item>
      </NotationBox>

      <h2>17.1 — Exact Universality: Rotations Plus CNOT</h2>
      <p className="mb-6 rounded-lg border border-primary/20 bg-primary/5 p-4 text-sm text-foreground/80">
        <strong>Study takeaway:</strong> single-qubit rotations plus CNOT can build any unitary exactly. A finite set like Clifford + T can approximate any unitary, and the cost of each extra digit of precision is small.
      </p>
      <p>
        Any unitary on <InlineMath math="n" /> qubits can be decomposed exactly into CNOT gates and single-qubit gates (Barenco and colleagues, 1995). For two qubits, at most three CNOTs are ever needed, plus single-qubit gates. The entangling gate is essential: without it, qubits that start in a product state stay in a product state, since single-qubit gates act on each factor separately.
      </p>
      <p>
        The catch is that &ldquo;any single-qubit rotation&rdquo; is a continuous family. Hardware and error-correcting codes prefer a small, fixed set of gates, which leads to approximation.
      </p>

      <h2>17.2 — Clifford Gates Are Not Enough</h2>
      <p>
        Clifford gates rearrange Pauli operators:
      </p>
      <BlockMath math="HXH = Z, \qquad HZH = X, \qquad SXS^\dagger = Y, \qquad \text{CNOT}\,(X\otimes I)\,\text{CNOT} = X\otimes X" />
      <p>
        Because of this, a Clifford circuit can be tracked by following how a handful of Pauli operators transform, which a classical computer does in polynomial time (the Gottesman–Knill theorem). Clifford circuits can create entanglement, even large GHZ states, and still offer no computational speedup.
      </p>
      <p>
        The T gate breaks this pattern: <InlineMath math="TXT^\dagger = \tfrac{1}{\sqrt2}(X + Y)" />, which is not a single Pauli. Adding T to <InlineMath math="\{H, S, \text{CNOT}\}" /> gives <strong>Clifford + T</strong>, a universal set. (Because <InlineMath math="S = T^2" />, the set <InlineMath math="\{H, T, \text{CNOT}\}" /> is enough.)
      </p>

      <h2>17.3 — How Much Does Approximation Cost?</h2>
      <p>
        The Solovay–Kitaev theorem guarantees that any single-qubit gate can be approximated to accuracy <InlineMath math="\varepsilon" /> with <InlineMath math="O(\log^c(1/\varepsilon))" /> gates from any universal set, for a small constant <InlineMath math="c" />. The point is that the cost grows only polylogarithmically: more digits of precision are cheap.
      </p>
      <p>
        For Clifford + T, modern number-theoretic synthesis (Ross and Selinger) approximates a Z rotation with about <InlineMath math="3\log_2(1/\varepsilon)" /> T gates. Worked example: for <InlineMath math="\varepsilon = 10^{-10}" />, <InlineMath math="\log_2(10^{10}) \approx 33.2" />, so about 100 T gates.
      </p>
      <p>
        T gates are the expensive part in fault-tolerant hardware, because they are usually implemented by consuming specially prepared &ldquo;magic states&rdquo; that must be distilled. That is why algorithms are compared by T-count: a Toffoli gate, for example, uses 7 T gates in its standard decomposition.
      </p>

      <h2>17.4 — Verifying Identities in the Playground</h2>
      <ol>
        <li><strong>T · T = S:</strong> both add a <InlineMath math="90^\circ" /> phase to <InlineMath math="|1\rangle" />. Sandwich them between H gates to make the phase visible: H → S → H and H → T → T → H give the same probabilities (0.5 each).</li>
        <li><strong>Four T gates make Z:</strong> H → T → T → T → T → H ends in <InlineMath math="|1\rangle" />, the same as H → Z → H.</li>
        <li><strong>HXH = Z:</strong> on <InlineMath math="|+\rangle" /> (prepared by H), X does nothing, while Z flips it to <InlineMath math="|-\rangle" />. Compare the state vectors.</li>
      </ol>

      <TryIt heading="17.5 — Try It: Build Z From T Gates">
        <p>
          Build H → T → T → T → T → H and confirm the qubit ends in <InlineMath math="|1\rangle" />. Then remove one T. The result is no longer a basis state: <InlineMath math="P(0) = (1 + \cos 135^\circ)/2 \approx 0.146" />. Each T is an eighth of a turn around the Bloch sphere&apos;s z-axis.
        </p>
      </TryIt>
    </>
  );
}
