'use client';
import { BlockMath, InlineMath } from '@/components/math';
import { NotationBox, TryIt } from '@/components/lesson';

export default function Lesson23Content() {
  return (
    <>
      <NotationBox>
        <NotationBox.Item heading="Physical model"><NotationBox.Text>A Hamiltonian describes the energy and interactions that drive a quantum system&apos;s evolution.</NotationBox.Text></NotationBox.Item>
        <NotationBox.Item heading="Evolution"><NotationBox.Code><NotationBox.Row math="|\psi(t)\rangle = e^{-iHt}|\psi(0)\rangle" label="time evolution" /></NotationBox.Code></NotationBox.Item>
      </NotationBox>
      <h2>32.1 — Simulating nature</h2>
      <p className="mb-6 rounded-lg border border-primary/20 bg-primary/5 p-4 text-sm text-foreground/80"><strong>Study takeaway:</strong> Hamiltonian simulation approximates the unitary time evolution generated by a physical Hamiltonian.</p>
      <p>For a closed quantum system, the Hamiltonian H determines how the state changes in time. A quantum computer can represent a model system and approximate the evolution operator, allowing observables to be estimated after a chosen time.</p>
      <BlockMath math="U(t)=e^{-iHt}" />
      <h2>32.2 — From Hamiltonian to gates</h2>
      <p>Most useful Hamiltonians are decomposed into sums of simpler terms. Product-formula methods approximate the exponential of a sum with short alternating evolutions, while more advanced methods use block encodings, qubitization, or linear-combination techniques.</p>
      <p>The central engineering tradeoff is simulation error versus circuit cost. Smaller time steps generally improve approximation but increase depth.</p>
      <TryIt heading="32.3 — Try It: Predict the evolution"><p>If H is diagonal in the computational basis, what changes during evolution: the basis-state probabilities, the phases, or both? Explain your prediction before using a simulator.</p></TryIt>
    </>
  );
}
