export type DemoOp = {
  gateId: string;
  targetQubit: number;
  controlQubit?: number;
};

export type LessonMeta = {
  id: number;
  title: string;
  slug: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  stage: string;
  prerequisites: number[];
  objective: string;
  xp: number;
  allowedGates: string[];
  challengeType: 'circuit' | 'read';
  upcoming?: boolean;
  demoOps?: DemoOp[];
};

export const LESSONS: LessonMeta[] = [
  {
    id: 1,
    title: 'Birth of Quantum Information',
    slug: 'birth-of-quantum-information',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [],
    objective: 'Understand why a qubit is more expressive than a classical bit.',
    xp: 100,
    allowedGates: ['H'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 2,
    title: 'Superposition',
    slug: 'superposition',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1],
    objective: 'Explain superposition as linear combination in Hilbert space.',
    xp: 100,
    allowedGates: ['H', 'X'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 3,
    title: 'Measurement',
    slug: 'measurement',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2],
    objective: 'Understand measurement as the bridge from quantum amplitudes to classical outcomes.',
    xp: 120,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 4,
    title: 'Entanglement',
    slug: 'entanglement',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 3],
    objective: 'See entanglement as non-factorizable joint state structure.',
    xp: 150,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
  },
  {
    id: 5,
    title: 'Interference',
    slug: 'interference',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 3],
    objective: 'Understand how relative phase makes amplitudes reinforce or cancel.',
    xp: 150,
    allowedGates: ['H', 'X', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  // ── Upcoming ───────────────────────────────────────────────────────────
  {
    id: 6,
    title: 'Quantum Gates & Unitarity',
    slug: 'quantum-gates-unitarity',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2],
    objective: 'Understand why all quantum gates must be unitary and reversible.',
    xp: 150,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
    ],
  },
  {
    id: 7,
    title: 'The Bloch Sphere',
    slug: 'bloch-sphere',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 5],
    objective: 'Map single-qubit state space to a geometric sphere.',
    xp: 150,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 8,
    title: 'Multi-Qubit Systems',
    slug: 'multi-qubit-systems',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [1, 2, 3, 4],
    objective: 'Describe joint states of n qubits using tensor products.',
    xp: 200,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
    ],
  },
  {
    id: 9,
    title: 'Quantum Circuits',
    slug: 'quantum-circuits',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [6, 8],
    objective: 'Read and build quantum circuits using the gate-wire formalism.',
    xp: 200,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
  },
  {
    id: 10,
    title: 'Phase Kickback',
    slug: 'phase-kickback',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [4, 5, 6],
    objective: 'Derive how a controlled gate transfers phase to the control qubit.',
    xp: 200,
    allowedGates: ['H', 'X', 'Z', 'S', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
      { gateId: 'H', targetQubit: 1 },
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 11,
    title: 'Decoherence',
    slug: 'decoherence',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [5, 9, 10],
    objective: 'Understand decoherence as loss of phase information caused by environmental coupling.',
    xp: 250,
    allowedGates: ['H', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 12,
    title: 'Quantum Noise and Errors',
    slug: 'quantum-noise-and-errors',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [5, 9, 10],
    objective: 'Model common quantum noise processes and how they produce logical errors.',
    xp: 250,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
    ],
  },
  {
    id: 13,
    title: "Deutsch-Jozsa Algorithm",
    slug: 'deutsch-jozsa',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [5, 9, 10],
    objective: 'Prove that one quantum query distinguishes constant from balanced functions.',
    xp: 250,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'H', targetQubit: 1 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 14,
    title: "Simon's Algorithm",
    slug: 'simons-algorithm',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [9, 11, 13],
    objective: 'Find hidden periods exponentially faster than any classical algorithm.',
    xp: 300,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 15,
    title: "Shor's Algorithm",
    slug: 'shors-algorithm',
    difficulty: 'advanced',
    stage: 'algorithms',
    prerequisites: [11, 14],
    objective: 'Factor integers in polynomial time using quantum period finding.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 16,
    title: 'Quantum Error Correction',
    slug: 'quantum-error-correction',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [8, 9, 4],
    objective: 'Encode logical qubits to protect against decoherence and gate errors.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 17,
    title: 'Quantum Teleportation',
    slug: 'quantum-teleportation',
    difficulty: 'intermediate',
    stage: 'advanced',
    prerequisites: [4, 9, 3],
    objective: 'Transmit an arbitrary qubit state using entanglement and classical bits.',
    xp: 300,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 18,
    title: 'Density Matrices',
    slug: 'density-matrices',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [7, 8, 3],
    objective: 'Represent mixed states and open quantum systems with density operators.',
    xp: 350,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 19,
    title: 'Quantum Complexity Theory',
    slug: 'quantum-complexity',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [12, 15],
    objective: 'Understand BQP, QMA, and where quantum advantage actually lives.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 20,
    title: 'Variational Quantum Algorithms',
    slug: 'variational-quantum-algorithms',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [9, 11, 18],
    objective: 'Design hybrid classical-quantum loops for near-term quantum hardware.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
];

export function getLessonBySlug(slug: string): LessonMeta | undefined {
  return LESSONS.find((l) => l.slug === slug);
}

export function getLessonById(id: number): LessonMeta | undefined {
  return LESSONS.find((l) => l.id === id);
}
