export type DemoOp = {
  gateId: string;
  targetQubit: number;
  controlQubit?: number;
};

export type LessonQuiz = {
  prompt: string;
  options: string[];
  answer: 'a' | 'b' | 'c' | 'd';
  explanation: string;
};

export type LessonMeta = {
  id: number;
  title: string;
  slug: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  stage: string;
  prerequisites: number[];
  objective: string;
  xp: number;
  allowedGates: string[];
  challengeType: 'circuit' | 'read';
  upcoming?: boolean;
  demoOps?: DemoOp[];
  quiz?: LessonQuiz;
};

const QUIZZES: Record<number, LessonQuiz> = {
  1: {
    prompt: 'What does a Hadamard gate do to |0⟩?',
    options: ['It leaves it unchanged', 'It turns it into |1⟩', 'It creates an equal superposition of |0⟩ and |1⟩', 'It measures it instantly'],
    answer: 'c',
    explanation: 'A Hadamard gate maps |0⟩ to an equal superposition of the two computational basis states.',
  },
  2: {
    prompt: 'Which statement best describes superposition?',
    options: ['A state that is definitely one outcome', 'A linear combination of basis states with amplitudes', 'A state that has no measurement uncertainty', 'A classical random bit'],
    answer: 'b',
    explanation: 'Superposition means the state is a coherent linear combination of basis states, not just a classical mixture.',
  },
  3: {
    prompt: 'What does measurement do in the simple picture of this course?',
    options: ['It creates new amplitudes', 'It converts quantum amplitudes into a classical outcome', 'It makes gates unitary', 'It removes all phase information forever'],
    answer: 'b',
    explanation: 'Measurement turns the quantum state into a concrete classical result according to the amplitudes.',
  },
  4: {
    prompt: 'What is entanglement?',
    options: ['A type of classical randomness', 'A joint state that cannot be written as a product of local states', 'A measurement error', 'A gate that always flips a qubit'],
    answer: 'b',
    explanation: 'Entangled states are non-factorizable: the joint state cannot be separated into independent local states.',
  },
  5: {
    prompt: 'Interference is mainly about which quantity?',
    options: ['The number of qubits', 'The relative phase of amplitudes', 'The speed of the gate', 'The amount of classical memory'],
    answer: 'b',
    explanation: 'Interference depends on the relative phase between amplitudes, which can make them reinforce or cancel.',
  },
  6: {
    prompt: 'Why must an ideal quantum gate be unitary?',
    options: ['Because it must be random', 'Because it must preserve normalization and reversibility', 'Because it can only act on one qubit', 'Because it cannot be represented as a matrix'],
    answer: 'b',
    explanation: 'Unitary gates preserve the total probability and are reversible before measurement.',
  },
  7: {
    prompt: 'What does the Bloch sphere represent?',
    options: ['The physical shape of a qubit', 'The geometry of a single-qubit pure state', 'The circuit depth', 'The classical bit value'],
    answer: 'b',
    explanation: 'The Bloch sphere is a geometric view of the state of a single qubit.',
  },
  8: {
    prompt: 'What grows exponentially when you add more qubits?',
    options: ['The number of gates in a circuit', 'The dimension of the state space', 'The strength of measurement', 'The size of a classical register'],
    answer: 'b',
    explanation: 'A system of n qubits lives in a Hilbert space of dimension 2^n.',
  },
  9: {
    prompt: 'What is a quantum circuit mainly used for?',
    options: ['To store classical data', 'To describe a sequence of gate operations', 'To create random noise', 'To replace measurement'],
    answer: 'b',
    explanation: 'A circuit is a visual and mathematical way to describe a sequence of quantum operations.',
  },
  10: {
    prompt: 'Phase kickback is most closely related to what effect?',
    options: ['A classical OR operation', 'A phase change that appears on the control qubit', 'A measurement collapse', 'A reset operation'],
    answer: 'b',
    explanation: 'Phase kickback transfers phase information into the control qubit through a controlled operation.',
  },
  11: {
    prompt: 'What does decoherence describe?',
    options: ['The loss of phase information due to environmental interaction', 'The creation of a new qubit', 'The exact reversal of a circuit', 'The equalization of all measurement outcomes'],
    answer: 'a',
    explanation: 'Decoherence is the loss of coherence caused by interaction with the environment.',
  },
  12: {
    prompt: 'What is a common consequence of quantum noise?',
    options: ['Perfect gate reversibility', 'Logical errors in the computation', 'No change in measurement statistics', 'A guaranteed entangled state'],
    answer: 'b',
    explanation: 'Noise can cause errors that change the intended computation.',
  },
  13: {
    prompt: 'What is the main goal of Deutsch-Jozsa?',
    options: ['To solve factoring', 'To distinguish constant from balanced functions with one query', 'To simulate Hamiltonians', 'To create superposition only'],
    answer: 'b',
    explanation: 'Deutsch-Jozsa uses quantum parallelism to decide a property of a function more efficiently than classical methods in the idealized case.',
  },
  14: {
    prompt: "What does Simon's algorithm exploit?",
    options: ['A classical sorting trick', 'An unknown periodicity hidden in a function', 'A fixed gate sequence', 'Only single-qubit gates'],
    answer: 'b',
    explanation: "Simon's algorithm uses quantum interference to reveal a hidden period in a black-box function.",
  },
  15: {
    prompt: "Shor's algorithm is famous for its use in which task?",
    options: ['Sorting numbers', 'Factoring integers', 'Searching a database', 'Sampling random states'],
    answer: 'b',
    explanation: "Shor's algorithm is best known for factoring integers efficiently using period finding.",
  },
  16: {
    prompt: 'Why do we use error correction in quantum computing?',
    options: ['To avoid all measurement', 'To protect logical qubits from noise and decoherence', 'To remove all entanglement', 'To simplify gate sets'],
    answer: 'b',
    explanation: 'Quantum error correction preserves fragile logical information despite errors.',
  },
  17: {
    prompt: 'What is quantum teleportation mainly using?',
    options: ['A classical memory channel only', 'Entanglement plus classical communication', 'Only unitary gates', 'Only measurement without entanglement'],
    answer: 'b',
    explanation: 'Teleportation uses entanglement and classical communication to transfer a state.',
  },
  18: {
    prompt: 'What do density matrices describe?',
    options: ['Only pure states', 'Mixed states and open systems', 'Only classical bits', 'Only one-qubit circuits'],
    answer: 'b',
    explanation: 'Density matrices describe statistical mixtures and open-system states.',
  },
  19: {
    prompt: 'What does BQP refer to?',
    options: ['A classical search algorithm', 'The class of problems efficiently solvable by a quantum computer', 'A noise model', 'A measurement basis'],
    answer: 'b',
    explanation: 'BQP is the complexity class for problems efficiently solvable by a quantum computer.',
  },
  20: {
    prompt: 'What is a variational algorithm mainly doing?',
    options: ['Ignoring classical compute', 'Optimizing parameters in a hybrid quantum-classical loop', 'Removing all measurements', 'Only using one gate'],
    answer: 'b',
    explanation: 'Variational methods use a quantum circuit and a classical optimizer together to find good parameters.',
  },
  21: {
    prompt: 'What is the quantum Fourier transform best known for?',
    options: ['Reversing a qubit', 'Re-expressing amplitudes in a frequency basis', 'Removing all phase', 'Replacing measurement'],
    answer: 'b',
    explanation: 'The QFT reshapes amplitudes into a frequency-like basis that is useful for period finding and phase estimation.',
  },
  22: {
    prompt: 'Phase estimation is mainly used to find what?',
    options: ['A random bit', 'The eigenvalue of a unitary operator', 'A classical register size', 'The number of qubits in memory'],
    answer: 'b',
    explanation: 'Phase estimation extracts an eigenvalue, often encoded as an angle, from a unitary operator.',
  },
  23: {
    prompt: 'Hamiltonian simulation is about modeling what?',
    options: ['Only classical sorting', 'The time evolution of a physical system', 'A static webpage', 'Only single-gate circuits'],
    answer: 'b',
    explanation: 'Hamiltonian simulation studies how a quantum system evolves under a Hamiltonian over time.',
  },
  24: {
    prompt: 'What makes a gate set universal?',
    options: ['It contains only measurement gates', 'It can approximate arbitrary unitary operations', 'It always uses one qubit', 'It removes entanglement'],
    answer: 'b',
    explanation: 'A universal gate set can approximate arbitrary unitary operations, usually using single-qubit control plus an entangling gate.',
  },
  25: {
    prompt: 'What determines the probability of a projective measurement outcome?',
    options: ['The number of gates only', 'The Born rule applied to the state and projector', 'The classical clock speed', 'The circuit label'],
    answer: 'b',
    explanation: 'For projector Pi_m, the probability is the expectation value of that projector in the current state.',
  },
  26: {
    prompt: 'What is the main role of the QFT in quantum algorithms?',
    options: ['To reset every qubit', 'To expose periodic structure through a basis change', 'To copy an unknown state', 'To replace all measurements'],
    answer: 'b',
    explanation: 'The QFT changes basis so phase and periodic structure can become concentrated measurement information.',
  },
  27: {
    prompt: 'Which gates appear in a standard QFT circuit decomposition?',
    options: ['Only X gates', 'Hadamards, controlled phase rotations, and swaps', 'Only measurements', 'Only CNOT gates'],
    answer: 'b',
    explanation: 'The usual decomposition combines Hadamards, controlled phase rotations, and a bit-reversal swap pattern.',
  },
  28: {
    prompt: 'What does phase estimation estimate?',
    options: ['A random classical bit', 'The eigenphase of a unitary operator', 'The number of gates in memory', 'A qubit temperature'],
    answer: 'b',
    explanation: 'Phase estimation uses controlled powers of a unitary and an inverse QFT to estimate its eigenphase.',
  },
  29: {
    prompt: 'What does Hamiltonian simulation approximate?',
    options: ['A sorting routine', 'The time-evolution operator exp(-iHt)', 'A measurement reset', 'A classical database'],
    answer: 'b',
    explanation: 'Hamiltonian simulation approximates the unitary evolution generated by a physical Hamiltonian.',
  },
  30: {
    prompt: 'What is VQE optimizing?',
    options: ['A random bit string', 'The expected energy of a parameterized trial state', 'The number of measurements to zero', 'Only circuit width'],
    answer: 'b',
    explanation: 'VQE varies circuit parameters to minimize the measured expectation value of a Hamiltonian.',
  },
  31: {
    prompt: 'What are the two alternating ingredients of QAOA?',
    options: ['A reset and a measurement', 'Cost evolution and mixer evolution', 'Two classical sorting passes', 'A Fourier transform and teleportation'],
    answer: 'b',
    explanation: 'QAOA alternates a problem-dependent cost layer with a mixer layer and optimizes their angles classically.',
  },
  32: {
    prompt: 'What does quantum annealing use to seek low-energy solutions?',
    options: ['Only random measurements', 'A slowly changing Hamiltonian', 'A fixed classical lookup table', 'Only teleportation'],
    answer: 'b',
    explanation: 'Quantum annealing interpolates between an easy initial Hamiltonian and a problem Hamiltonian.',
  },
  33: {
    prompt: 'Why must adiabatic evolution be sufficiently slow?',
    options: ['To increase classical memory', 'To reduce transitions away from the intended eigenstate', 'To remove all phase', 'To force every state to be equal'],
    answer: 'b',
    explanation: 'Slow evolution helps the system remain near the instantaneous ground state when the spectral gap permits it.',
  },
  34: {
    prompt: 'What is phase kickback?',
    options: ['A classical OR operation', 'A phase acquired by a control branch through a controlled eigenvalue operation', 'A measurement reset', 'A qubit copy operation'],
    answer: 'b',
    explanation: 'When the target is an eigenstate, its eigenphase appears as relative phase on the control register.',
  },
  35: {
    prompt: 'Why do quantum algorithms engineer interference?',
    options: ['To hide all amplitudes', 'To amplify useful outcomes and cancel unhelpful paths', 'To avoid unitary evolution', 'To make measurement unnecessary'],
    answer: 'b',
    explanation: 'Algorithms arrange amplitude and relative phase so interference changes the final measurement distribution in a useful way.',
  },
  36: {
    prompt: 'What does the no-cloning theorem say?',
    options: ['Quantum states can never be measured', 'An unknown quantum state cannot be copied perfectly', 'Only classical bits can be copied', 'Entangled states cannot exist'],
    answer: 'b',
    explanation: 'Quantum mechanics does not allow a universal operation that makes a perfect copy of an arbitrary unknown state.',
  },
  37: {
    prompt: 'What does Grover\'s algorithm amplify?',
    options: ['Every answer equally', 'The probability of marked solutions', 'Only the global phase', 'The number of physical qubits'],
    answer: 'b',
    explanation: 'The oracle marks candidate solutions with phase, and the diffusion step increases the amplitude of marked states under the search assumptions.',
  },
  38: {
    prompt: 'What makes BB84 secure in its idealized model?',
    options: ['Unknown quantum states can be copied', 'An eavesdropper cannot measure incompatible states without introducing detectable disturbance', 'The channel never has noise', 'Classical encryption is unnecessary'],
    answer: 'b',
    explanation: 'BB84 uses incompatible preparation and measurement bases; interception changes statistics that legitimate users can test.',
  },
  39: {
    prompt: 'What is a key difference between quantum hardware platforms?',
    options: ['They all use identical control and readout methods', 'They use different physical qubits, control methods, connectivity, and error profiles', 'They do not need calibration', 'They cannot run circuits'],
    answer: 'b',
    explanation: 'Superconducting circuits, trapped ions, neutral atoms, photons, and other platforms have different engineering tradeoffs.',
  },
  40: {
    prompt: 'What does a quantum compiler or transpiler do?',
    options: ['Change a quantum result after measurement', 'Map an abstract circuit to native gates and hardware constraints', 'Remove the need for error correction', 'Copy unknown quantum states'],
    answer: 'b',
    explanation: 'Compilation preserves the intended operation while adapting it to native gates, connectivity, scheduling, and hardware limits.',
  },
};

export function getLessonQuiz(lessonId: number): LessonQuiz | undefined {
  return QUIZZES[lessonId];
}

export const LESSONS: LessonMeta[] = [
  {
    id: 1,
    title: 'Birth of Quantum Information',
    slug: 'birth-of-quantum-information',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [],
    objective: 'Understand why a qubit is more expressive than a classical bit.',
    xp: 100,
    allowedGates: ['H'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(1),
  },
  {
    id: 2,
    title: 'Superposition',
    slug: 'superposition',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1],
    objective: 'Explain superposition as linear combination in Hilbert space.',
    xp: 100,
    allowedGates: ['H', 'X'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(2),
  },
  {
    id: 3,
    title: 'Measurement',
    slug: 'measurement',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2],
    objective: 'Understand measurement as the bridge from quantum amplitudes to classical outcomes.',
    xp: 120,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(3),
  },
  {
    id: 4,
    title: 'Entanglement',
    slug: 'entanglement',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 3],
    objective: 'See entanglement as non-factorizable joint state structure.',
    xp: 150,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
    quiz: getLessonQuiz(4),
  },
  {
    id: 5,
    title: 'Interference',
    slug: 'interference',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 3],
    objective: 'Understand how relative phase makes amplitudes reinforce or cancel.',
    xp: 150,
    allowedGates: ['H', 'X', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(5),
  },
  // ── Upcoming ───────────────────────────────────────────────────────────
  {
    id: 6,
    title: 'Quantum Gates & Unitarity',
    slug: 'quantum-gates-unitarity',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2],
    objective: 'Understand why all quantum gates must be unitary and reversible.',
    xp: 150,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(6),
  },
  {
    id: 7,
    title: 'The Bloch Sphere',
    slug: 'bloch-sphere',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 5],
    objective: 'Map single-qubit state space to a geometric sphere.',
    xp: 150,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(7),
  },
  {
    id: 8,
    title: 'Multi-Qubit Systems',
    slug: 'multi-qubit-systems',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [1, 2, 3],
    objective: 'Describe joint states of n qubits using tensor products.',
    xp: 200,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
    ],
    quiz: getLessonQuiz(8),
  },
  {
    id: 9,
    title: 'Quantum Circuits',
    slug: 'quantum-circuits',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [6, 8],
    objective: 'Read and build quantum circuits using the gate-wire formalism.',
    xp: 200,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
    quiz: getLessonQuiz(9),
  },
  {
    id: 10,
    title: 'Phase Kickback',
    slug: 'phase-kickback',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [4, 5, 6],
    objective: 'Derive how a controlled gate transfers phase to the control qubit.',
    xp: 200,
    allowedGates: ['H', 'X', 'Z', 'S', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
      { gateId: 'H', targetQubit: 1 },
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(10),
  },
  {
    id: 11,
    title: 'Decoherence',
    slug: 'decoherence',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [5, 9, 10],
    objective: 'Understand decoherence as loss of phase information caused by environmental coupling.',
    xp: 250,
    allowedGates: ['H', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(11),
  },
  {
    id: 12,
    title: 'Quantum Noise and Errors',
    slug: 'quantum-noise-and-errors',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [5, 9, 10],
    objective: 'Model common quantum noise processes and how they produce logical errors.',
    xp: 250,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(12),
  },
  {
    id: 13,
    title: "Deutsch-Jozsa Algorithm",
    slug: 'deutsch-jozsa',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [5, 9, 10],
    objective: 'Prove that one quantum query distinguishes constant from balanced functions.',
    xp: 250,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'H', targetQubit: 1 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(13),
  },
  {
    id: 14,
    title: "Simon's Algorithm",
    slug: 'simons-algorithm',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [9, 11, 13],
    objective: 'Recover a hidden XOR period with an exponential query advantage in the standard oracle model.',
    xp: 300,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(14),
  },
  {
    id: 15,
    title: "Shor's Algorithm",
    slug: 'shors-algorithm',
    difficulty: 'advanced',
    stage: 'algorithms',
    prerequisites: [11, 14],
    objective: 'Understand how ideal fault-tolerant quantum period finding can factor integers in polynomial time.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(15),
  },
  {
    id: 16,
    title: 'Quantum Error Correction',
    slug: 'quantum-error-correction',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [8, 9, 4],
    objective: 'Encode logical qubits to protect against decoherence and gate errors.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(16),
  },
  {
    id: 17,
    title: 'Quantum Teleportation',
    slug: 'quantum-teleportation',
    difficulty: 'intermediate',
    stage: 'advanced',
    prerequisites: [4, 9, 3],
    objective: 'Transmit an arbitrary qubit state using entanglement and classical bits.',
    xp: 300,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(17),
  },
  {
    id: 18,
    title: 'Density Matrices',
    slug: 'density-matrices',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [7, 8, 3],
    objective: 'Represent mixed states and open quantum systems with density operators.',
    xp: 350,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(18),
  },
  {
    id: 19,
    title: 'Quantum Complexity Theory',
    slug: 'quantum-complexity',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [12, 15],
    objective: 'Understand BQP, QMA, and where quantum advantage actually lives.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(19),
  },
  {
    id: 20,
    title: 'Variational Quantum Algorithms',
    slug: 'variational-quantum-algorithms',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [9, 11, 18],
    objective: 'Design hybrid classical-quantum loops for near-term quantum hardware.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(20),
  },
  {
    id: 21,
    title: 'Quantum Fourier Transform',
    slug: 'quantum-fourier-transform',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [9],
    objective: 'Understand why the quantum Fourier transform is central to many quantum algorithms.',
    xp: 450,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(21),
  },
  {
    id: 22,
    title: 'Phase Estimation',
    slug: 'phase-estimation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [21],
    objective: 'See how phase estimation turns eigenvalue information into useful algorithmic output.',
    xp: 450,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(22),
  },
  {
    id: 23,
    title: 'Hamiltonian Simulation',
    slug: 'hamiltonian-simulation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [16, 20],
    objective: 'Understand how quantum computers simulate the dynamics of physical systems.',
    xp: 500,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(23),
  },
  {
    id: 24,
    title: 'Universal Gate Sets',
    slug: 'universal-gate-sets',
    difficulty: 'intermediate',
    stage: 'advanced',
    prerequisites: [6, 9, 10],
    objective: 'Understand how a small collection of gates can approximate arbitrary quantum operations.',
    xp: 350,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(24),
  },
  {
    id: 25,
    title: 'Measurement Theory (Deep)',
    slug: 'measurement-theory-deep',
    difficulty: 'intermediate',
    stage: 'advanced',
    prerequisites: [3, 18],
    objective: 'Connect projective measurement, observables, Born probabilities, and post-measurement states.',
    xp: 350,
    allowedGates: ['H', 'X', 'Y', 'Z'],
    challengeType: 'read',
    quiz: getLessonQuiz(25),
  },
  {
    id: 26,
    title: 'Quantum Fourier Transform (QFT)',
    slug: 'quantum-fourier-transform-qft',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [21],
    objective: 'Understand the QFT as a change of basis that exposes periodic structure.',
    xp: 450,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(26),
  },
  {
    id: 27,
    title: 'QFT Circuit Implementation',
    slug: 'qft-circuit-implementation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [26],
    objective: 'Decompose the quantum Fourier transform into controlled phase rotations and swaps.',
    xp: 450,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'circuit',
    quiz: getLessonQuiz(27),
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 1 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
  },
  {
    id: 28,
    title: 'Phase Estimation',
    slug: 'phase-estimation-deep',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [22, 26, 27],
    objective: 'Use controlled unitary operations and the inverse QFT to estimate eigenphases.',
    xp: 500,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(28),
  },
  {
    id: 29,
    title: 'Hamiltonian Simulation',
    slug: 'hamiltonian-simulation-deep',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [23, 24],
    objective: 'Approximate physical time evolution with decomposed quantum operations.',
    xp: 500,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(29),
  },
  {
    id: 30,
    title: 'Variational Quantum Eigensolver (VQE)',
    slug: 'variational-quantum-eigensolver-vqe',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [20],
    objective: 'Estimate ground-state energies with a parameterized circuit and a classical optimizer.',
    xp: 500,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S'],
    challengeType: 'circuit',
    quiz: getLessonQuiz(30),
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 31,
    title: 'Quantum Approximate Optimization Algorithm (QAOA)',
    slug: 'quantum-approximate-optimization-algorithm-qaoa',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [20, 24],
    objective: 'Build a hybrid algorithm that searches combinatorial problems through alternating cost and mixer layers.',
    xp: 500,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(31),
  },
  {
    id: 32,
    title: 'Quantum Annealing',
    slug: 'quantum-annealing',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [29, 31],
    objective: 'Distinguish adiabatic optimization from gate-based variational methods.',
    xp: 450,
    allowedGates: [],
    challengeType: 'read',
    quiz: getLessonQuiz(32),
  },
  {
    id: 33,
    title: 'Adiabatic Quantum Computation',
    slug: 'adiabatic-quantum-computation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [14, 29, 32],
    objective: 'Understand computation as controlled continuous evolution between Hamiltonians.',
    xp: 450,
    allowedGates: [],
    challengeType: 'read',
    quiz: getLessonQuiz(33),
  },
  {
    id: 34,
    title: 'Phase Kickback',
    slug: 'phase-kickback-advanced',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [10, 22, 28],
    objective: 'Derive phase kickback as the mechanism behind several quantum algorithmic speedups.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(34),
  },
  {
    id: 35,
    title: 'Phase, Amplitude, and Interference (Advanced View)',
    slug: 'phase-amplitude-and-interference-advanced-view',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [5, 18, 34],
    objective: 'Synthesize amplitude, phase, and interference into one practical model of quantum computation.',
    xp: 500,
    allowedGates: ['H', 'X', 'Z', 'S', 'T'],
    challengeType: 'read',
    quiz: getLessonQuiz(35),
  },
  {
    id: 36,
    title: 'The No-Cloning Theorem',
    slug: 'no-cloning-theorem',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [2, 3, 6],
    objective: 'Understand why an unknown quantum state cannot be copied perfectly and how this differs from classical duplication.',
    xp: 250,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(36),
  },
  {
    id: 37,
    title: "Grover's Search Algorithm",
    slug: 'grovers-search-algorithm',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [5, 9, 10],
    objective: 'See how an oracle and diffusion step amplify marked solutions in an unstructured search problem.',
    xp: 350,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(37),
  },
  {
    id: 38,
    title: 'Quantum Cryptography and BB84',
    slug: 'quantum-cryptography-bb84',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [3, 4, 9, 36],
    objective: 'Explain how BB84 uses incompatible measurement bases to detect eavesdropping in an idealized key-distribution protocol.',
    xp: 350,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    quiz: getLessonQuiz(38),
  },
  {
    id: 39,
    title: 'Quantum Hardware Platforms',
    slug: 'quantum-hardware-platforms',
    difficulty: 'intermediate',
    stage: 'advanced',
    prerequisites: [11, 12, 16],
    objective: 'Compare major physical qubit platforms and the control, connectivity, and error tradeoffs that shape their architectures.',
    xp: 300,
    allowedGates: [],
    challengeType: 'read',
    quiz: getLessonQuiz(39),
  },
  {
    id: 40,
    title: 'Compilation and Transpilation',
    slug: 'quantum-compilation-and-transpilation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [9, 24, 27, 39],
    objective: 'Follow how an abstract circuit becomes a hardware-aware program with native gates, routing, scheduling, and measurable costs.',
    xp: 350,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T', 'CNOT'],
    challengeType: 'read',
    quiz: getLessonQuiz(40),
  },
];

// IDs stay stable for routes, prerequisites, quizzes, and progress. This array is
// the student-facing sequence; content filenames use its 1-based display order.
const CURRICULUM_ORDER = [
  1, 2, 3, 6, 5, 7, 8, 4, 9, 17, 36, 10, 11, 12, 18, 25, 24, 16,
  13, 14, 37, 21, 26, 27, 22, 28, 15, 19, 20, 30, 31, 23, 29, 32, 33,
  38, 39, 40, 34, 35,
] as const;

export const ORDERED_LESSONS: LessonMeta[] = CURRICULUM_ORDER.map((id) => {
  const lesson = LESSONS.find((item) => item.id === id);
  if (!lesson) throw new Error(`Missing lesson ${id} from curriculum order.`);
  return lesson;
});

export function getDisplayLessonNumber(lessonId: number): number {
  const index = ORDERED_LESSONS.findIndex((lesson) => lesson.id === lessonId);
  return index >= 0 ? index + 1 : lessonId;
}

export function getNextLesson(lessonId: number): LessonMeta | undefined {
  const index = ORDERED_LESSONS.findIndex((lesson) => lesson.id === lessonId);
  return index >= 0 ? ORDERED_LESSONS[index + 1] : undefined;
}

export function getPreviousLesson(lessonId: number): LessonMeta | undefined {
  const index = ORDERED_LESSONS.findIndex((lesson) => lesson.id === lessonId);
  return index > 0 ? ORDERED_LESSONS[index - 1] : undefined;
}

export function getLessonBySlug(slug: string): LessonMeta | undefined {
  return LESSONS.find((l) => l.slug === slug);
}

export function getLessonById(id: number): LessonMeta | undefined {
  return LESSONS.find((l) => l.id === id);
}
