export type LessonQiskitSnippet = {
  title: string;
  note: string;
  code: string;
};

const circuit = (body: string) => `from qiskit import QuantumCircuit\nfrom qiskit.primitives import StatevectorSampler\n\ncircuit = QuantumCircuit(2)\n${body}\ncircuit.measure_all()\n\nsampler = StatevectorSampler()\nresult = sampler.run([circuit], shots=1024).result()[0]\nprint(circuit)\nprint(result.data.meas.get_counts())`;

export const LESSON_QISKIT_SNIPPETS: Record<number, LessonQiskitSnippet> = {
  1: { title: 'Create a first superposition', note: 'The Hadamard gate turns |0> into equal 0/1 measurement probabilities.', code: circuit('circuit.h(0)') },
  2: { title: 'Control a superposition', note: 'Change the gate or shots and compare the measured distribution.', code: circuit('circuit.h(0)\ncircuit.x(1)') },
  3: { title: 'Measure a prepared state', note: 'Measurement converts the amplitudes prepared by H into sampled classical results.', code: circuit('circuit.h(0)') },
  4: { title: 'Build a Bell pair', note: 'The H-CX pattern creates correlated 00 and 11 outcomes.', code: circuit('circuit.h(0)\ncircuit.cx(0, 1)') },
  5: { title: 'Make interference visible', note: 'The Z phase between two H gates changes the final measurement result.', code: circuit('circuit.h(0)\ncircuit.z(0)\ncircuit.h(0)') },
  6: { title: 'Use reversible gates', note: 'Applying H twice returns the qubit to its starting state because H squared is identity.', code: circuit('circuit.h(0)\ncircuit.h(0)') },
  7: { title: 'Move around the Bloch sphere', note: 'RY rotates a qubit by a chosen angle around the Y axis.', code: `from math import pi\nfrom qiskit import QuantumCircuit\nfrom qiskit.primitives import StatevectorSampler\n\ncircuit = QuantumCircuit(1)\ncircuit.ry(pi / 2, 0)\ncircuit.measure_all()\n\nresult = StatevectorSampler().run([circuit], shots=1024).result()[0]\nprint(result.data.meas.get_counts())` },
  8: { title: 'Combine two qubits', note: 'Tensor-product structure becomes visible when a two-qubit circuit is measured.', code: circuit('circuit.h(0)\ncircuit.x(1)') },
  9: { title: 'Read a circuit as operations', note: 'The gates execute in order from top to bottom in the circuit diagram.', code: circuit('circuit.h(0)\ncircuit.cx(0, 1)\ncircuit.x(1)') },
  10: { title: 'See phase kickback', note: 'The H-X-CX-H pattern transfers a target eigenvalue into a control phase.', code: circuit('circuit.h(0)\ncircuit.x(1)\ncircuit.h(1)\ncircuit.cx(0, 1)\ncircuit.h(1)') },
  11: { title: 'Compare a coherent phase change', note: 'This is a reversible Z phase flip, used as a clean contrast with stochastic decoherence.', code: circuit('circuit.h(0)\ncircuit.z(0)\ncircuit.h(0)') },
  12: { title: 'Model a simple bit-flip pattern', note: 'The X gate is a deterministic error sketch; real noise requires a channel or hardware execution.', code: circuit('circuit.h(0)\ncircuit.x(0)') },
  13: { title: 'Run a balanced Deutsch-Jozsa oracle', note: 'This complete 2-input example uses an ancilla prepared in |-> and the balanced oracle f(x)=x₀.', code: `from qiskit import QuantumCircuit\nfrom qiskit.primitives import StatevectorSampler\n\ncircuit = QuantumCircuit(3)\ncircuit.x(2)\ncircuit.h([0, 1, 2])\ncircuit.cx(0, 2)\ncircuit.h([0, 1])\ncircuit.measure_all()\n\nresult = StatevectorSampler().run([circuit], shots=1024).result()[0]\nprint(result.data.meas.get_counts())\n# The two input qubits should show a nonzero pattern; Qiskit displays bit strings in register order.` },
  14: { title: 'Inspect a Simon-style oracle', note: 'This is a small hidden-XOR oracle sketch. A full Simon run repeats samples and solves y·s = 0 mod 2.', code: `from qiskit import QuantumCircuit\nfrom qiskit.primitives import StatevectorSampler\n\ncircuit = QuantumCircuit(4)\ncircuit.h([0, 1])\n# Toy oracle: copy the parity x0 XOR x1 into both output wires.\ncircuit.cx(0, 2)\ncircuit.cx(1, 2)\ncircuit.cx(0, 3)\ncircuit.cx(1, 3)\ncircuit.h([0, 1])\ncircuit.measure_all()\n\nresult = StatevectorSampler().run([circuit], shots=1024).result()[0]\nprint(result.data.meas.get_counts())` },
  15: { title: 'Prepare a period-finding phase pattern', note: 'A complete Shor implementation needs an arithmetic oracle; this sketch focuses on controlled phase structure.', code: circuit('circuit.h(0)\ncircuit.cp(3.141592653589793 / 2, 0, 1)\ncircuit.h(1)') },
  16: { title: 'Encode a repetition-code sketch', note: 'This encodes a known computational-basis bit into three physical qubits; a full code also extracts syndromes and corrects errors.', code: `from qiskit import QuantumCircuit\nfrom qiskit.primitives import StatevectorSampler\n\ncircuit = QuantumCircuit(3)\ncircuit.x(0)\ncircuit.cx(0, 1)\ncircuit.cx(0, 2)\ncircuit.measure_all()\n\nresult = StatevectorSampler().run([circuit], shots=1024).result()[0]\nprint(result.data.meas.get_counts())\n# This prepares 111. Try inserting an X on one encoded qubit.` },
  17: { title: 'Prepare the teleportation ingredients', note: 'This creates an input state and Bell pair; a complete protocol also measures and classically corrects.', code: `from qiskit import QuantumCircuit\n\ncircuit = QuantumCircuit(3)\ncircuit.ry(0.7, 0)\ncircuit.h(1)\ncircuit.cx(1, 2)\ncircuit.cx(0, 1)\ncircuit.h(0)\nprint(circuit)` },
  18: { title: 'Prepare a mixed-state experiment', note: 'Run the same circuit with different preparations and compare density-matrix predictions.', code: `from qiskit import QuantumCircuit\nfrom qiskit.quantum_info import DensityMatrix\n\ncircuit = QuantumCircuit(1)\ncircuit.h(0)\nstate = DensityMatrix.from_instruction(circuit)\nprint(state)` },
  19: { title: 'Compare circuit growth', note: 'Complexity is about how resources scale as the input grows, not only the output of one circuit.', code: `from qiskit import QuantumCircuit\n\nfor qubits in [2, 4, 8]:\n    circuit = QuantumCircuit(qubits)\n    for index in range(qubits):\n        circuit.h(index)\n    print(qubits, circuit.size(), 'gates')` },
  20: { title: 'Build a variational ansatz', note: 'A classical optimizer would change theta and repeatedly measure the resulting energy estimate.', code: `from qiskit import QuantumCircuit\n\nfor theta in [0.0, 0.5, 1.0]:\n    circuit = QuantumCircuit(1)\n    circuit.ry(theta, 0)\n    print(f"theta={theta}")\n    print(circuit)` },
  21: { title: 'Start a two-qubit Fourier circuit', note: 'This is a compact QFT teaching circuit using Hadamards and a controlled phase rotation.', code: circuit('circuit.h(0)\ncircuit.cp(3.141592653589793 / 2, 1, 0)\ncircuit.h(1)') },
  22: { title: 'Create a phase-estimation control pattern', note: 'A complete phase-estimation routine also needs controlled powers and an inverse QFT.', code: circuit('circuit.h(0)\ncircuit.cp(3.141592653589793 / 2, 0, 1)\ncircuit.h(0)') },
  23: { title: 'Simulate simple Z evolution', note: 'RZ is the exact one-qubit evolution for a Z-like Hamiltonian, up to a global phase convention.', code: circuit('circuit.h(0)\ncircuit.rz(0.8, 0)') },
  24: { title: 'Try a universal gate set', note: 'H, T, and CX provide basis change, non-Clifford phase, and entanglement.', code: circuit('circuit.h(0)\ncircuit.t(0)\ncircuit.cx(0, 1)') },
  25: { title: 'Measure in a different basis', note: 'A final H changes a computational-basis measurement into an X-basis measurement.', code: circuit('circuit.h(0)\ncircuit.h(0)') },
  26: { title: 'Reverse a Fourier-style pattern', note: 'The inverse QFT is a basis change that turns organized phase into measurable structure.', code: circuit('circuit.h(0)\ncircuit.cp(-3.141592653589793 / 2, 1, 0)\ncircuit.h(1)') },
  27: { title: 'Inspect QFT circuit ingredients', note: 'Controlled phase rotations become smaller as the separation between qubits increases.', code: circuit('circuit.h(0)\ncircuit.cp(3.141592653589793 / 2, 1, 0)\ncircuit.h(1)') },
  28: { title: 'Encode a phase fraction', note: 'The control qubit accumulates a relative phase that an inverse QFT would decode into bits.', code: circuit('circuit.h(0)\ncircuit.cp(3.141592653589793 / 2, 0, 1)\ncircuit.h(0)') },
  29: { title: 'Alternate Hamiltonian terms', note: 'Alternating small rotations is a simple Trotter-style teaching model for composed evolution.', code: circuit('circuit.rz(0.2, 0)\ncircuit.rx(0.2, 0)\ncircuit.rz(0.2, 0)\ncircuit.rx(0.2, 0)') },
  30: { title: 'Scan a VQE parameter', note: 'This does not measure a chemistry Hamiltonian, but it shows the parameterized trial-state loop.', code: `from qiskit import QuantumCircuit\n\nfor theta in [0.0, 0.5, 1.0, 1.5]:\n    circuit = QuantumCircuit(1)\n    circuit.ry(theta, 0)\n    print(f"theta={theta}, circuit depth={circuit.depth()}")` },
  31: { title: 'Alternate QAOA-style layers', note: 'The cost and mixer layers are represented here by phase and X rotations on a small register.', code: circuit('circuit.h(0)\ncircuit.h(1)\ncircuit.cx(0, 1)\ncircuit.rz(0.6, 1)\ncircuit.cx(0, 1)\ncircuit.rx(0.8, 0)\ncircuit.rx(0.8, 1)') },
  32: { title: 'Interpolate an annealing angle', note: 'Changing the schedule changes the rotation gradually; a real annealer uses a time-dependent Hamiltonian.', code: `from qiskit import QuantumCircuit\n\nfor s in [0.0, 0.5, 1.0]:\n    circuit = QuantumCircuit(1)\n    circuit.ry(s * 3.141592653589793, 0)\n    print(f"s={s}")\n    print(circuit)` },
  33: { title: 'Compare slow and fast schedules', note: 'This circuit sketch invites you to compare a gradual sequence with one large rotation.', code: circuit('circuit.ry(0.25, 0)\ncircuit.ry(0.25, 0)\ncircuit.ry(0.25, 0)\ncircuit.ry(0.25, 0)') },
  34: { title: 'Make kickback measurable', note: 'The target is prepared in an X eigenstate so the controlled operation contributes a phase to the control.', code: circuit('circuit.h(0)\ncircuit.x(1)\ncircuit.h(1)\ncircuit.cx(0, 1)\ncircuit.h(1)\ncircuit.h(0)') },
  35: { title: 'Amplify or cancel paths', note: 'Changing the relative phase between two paths changes whether they reinforce or cancel.', code: circuit('circuit.h(0)\ncircuit.z(0)\ncircuit.h(0)') },
    36: { title: 'See why CNOT is not a universal copier', note: 'CNOT copies computational-basis correlation but sends a superposition input to an entangled state.', code: circuit('circuit.h(0)\\ncircuit.cx(0, 1)') },
    37: { title: 'Sketch Grover amplification', note: 'A full implementation needs a problem-specific phase oracle and diffusion operator; this code shows the starting register only.', code: `from qiskit import QuantumCircuit\n\nqubits = 2\ncircuit = QuantumCircuit(qubits)\ncircuit.h(range(qubits))\nprint(circuit)\n# Add a reversible phase oracle and diffusion operator for a chosen marked state.` },
    38: { title: 'Write the BB84 basis table', note: 'This compact classical sketch illustrates basis choices and sifting; it is not a security implementation.', code: `import random\n\nalice_bits = [random.randrange(2) for _ in range(8)]\nalice_bases = [random.choice(['Z', 'X']) for _ in alice_bits]\nbob_bases = [random.choice(['Z', 'X']) for _ in alice_bits]\nkept = [index for index, (alice, bob) in enumerate(zip(alice_bases, bob_bases)) if alice == bob]\nprint('Alice bases:', alice_bases)\nprint('Bob bases:  ', bob_bases)\nprint('Kept indexes:', kept)\n# A real protocol needs quantum transmission, authentication, error testing, and privacy amplification.` },
    39: { title: 'Record hardware tradeoffs', note: 'Use a table rather than a single qubit-count headline when comparing physical platforms.', code: `platforms = {\n    'superconducting': {'speed': 'fast', 'coherence': 'shorter', 'control': 'microwave'},\n    'trapped_ion': {'speed': 'slower', 'coherence': 'longer', 'control': 'laser'},\n    'photonic': {'speed': 'fast propagation', 'coherence': 'loss-limited', 'control': 'optical'},\n}\nfor name, metrics in platforms.items():\n    print(name, metrics)` },
    40: { title: 'Inspect a hardware-aware circuit', note: 'Qiskit transpilation maps an abstract circuit to a target basis; the exact result depends on the backend and settings.', code: `from qiskit import QuantumCircuit, transpile\n\ncircuit = QuantumCircuit(2)\ncircuit.h(0)\ncircuit.cx(0, 1)\ncompiled = transpile(circuit, basis_gates=['rz', 'sx', 'x', 'cx'], optimization_level=1)\nprint(compiled)\nprint('depth:', compiled.depth())` },
};
