export type LessonAnalogy = {
  title: string;
  analogy: string;
  captures: string;
  limitations: string;
  formalConnection: string;
  formalMath?: string;
};

export const LESSON_ANALOGIES: Record<number, LessonAnalogy> = {
  1: {
    title: 'A light switch versus a dimmer with a direction',
    analogy: 'A classical bit is a light switch: it is either off or on. Describing a qubit is more like describing a dimmer that also has a direction dial. You need to say how much weight each setting has, and the direction matters when two settings are later combined.',
    captures: 'A qubit state is described by continuous amplitudes, including a relative phase, while a classical bit is described by one of two values.',
    limitations: 'You can read a dimmer at a glance, but measuring a qubit returns only 0 or 1. A single qubit cannot be used to store and retrieve more than one classical bit, and amplitudes are complex numbers, not brightness levels.',
    formalConnection: 'A qubit state is a normalized linear combination of the two basis states, with complex amplitudes whose squared magnitudes sum to one.',
    formalMath: '|\\psi\\rangle=\\alpha|0\\rangle+\\beta|1\\rangle,\\quad |\\alpha|^2+|\\beta|^2=1',
  },
  2: {
    title: 'A chord, not a hidden coin',
    analogy: 'A musical chord is one sound made from several notes at once, each with its own strength. It is not a single note that was secretly chosen and hidden from you.',
    captures: 'Superposition is one definite state built as a weighted combination of basis states. That is different from a classical mixture, where one outcome is already fixed but unknown.',
    limitations: 'You can hear every note in a chord, while measuring a superposition returns just one basis outcome. The weights are complex amplitudes whose phases matter, not loudness levels.',
    formalConnection: 'The Hadamard gate turns a basis state into an equal-weight superposition. Its relative phase distinguishes it from other states with the same measurement probabilities.',
    formalMath: 'H|0\\rangle=|+\\rangle=\\tfrac{1}{\\sqrt2}(|0\\rangle+|1\\rangle)',
  },
  3: {
    title: 'Roll-call and the classical record',
    analogy: 'A teacher asks a student to answer roll-call. Before the answer, the register has several possible entries; after the answer, one classical result is recorded.',
    captures: 'Measurement is the bridge from a richer quantum state description to one classical outcome that can be stored and communicated.',
    limitations: 'The teacher does not physically force the student to become present or absent. Quantum measurement is a physical interaction, and the post-measurement state depends on the outcome.',
    formalConnection: 'For projectors, the probability of an outcome is an expectation value, and the state update is basis-dependent.',
    formalMath: '\\Pr(i)=\\langle\\psi|\\Pi_i|\\psi\\rangle',
  },
  4: {
    title: 'A combination lock described only as a whole',
    analogy: 'Picture a two-dial lock that opens only when the dials match, either both on 0 or both on 1. You can state the rule for the pair precisely while being unable to say what either dial reads on its own.',
    captures: 'In an entangled state the information lives in the joint description. Neither qubit has a definite state of its own, yet measurement results are correlated.',
    limitations: 'A real lock has definite settings someone could inspect in advance. Bell tests show that entangled correlations cannot be explained by values fixed ahead of time, and entanglement still cannot be used to send a message faster than light.',
    formalConnection: 'A Bell state cannot be written as a tensor product of two single-qubit states.',
    formalMath: '|\\Phi^+\\rangle=\\tfrac{1}{\\sqrt2}(|00\\rangle+|11\\rangle)\\ne|a\\rangle\\otimes|b\\rangle',
  },
  5: {
    title: 'Traffic signals and coordinated flow',
    analogy: 'A sequence of traffic lights can create a green wave, or badly timed signals can repeatedly interrupt the same journey. Coordination changes the final flow.',
    captures: 'Interference depends on how coherent paths line up: contributions can reinforce or cancel when they reach the same outcome.',
    limitations: 'Traffic is a classical flow, not a wavefunction. Quantum amplitudes are complex numbers that combine before their squared magnitudes become probabilities.',
    formalConnection: 'Amplitudes add first, then probabilities are computed. The cross term can be constructive or destructive.',
    formalMath: '|a+b|^2=|a|^2+|b|^2+2\\operatorname{Re}(a^*b)',
  },
  6: {
    title: 'Twisting a Rubik’s cube',
    analogy: 'Every twist of a Rubik’s cube can be undone by the opposite twist, and no twist ever adds or removes a sticker. Moves only rearrange what is already there.',
    captures: 'Quantum gates are reversible and preserve the total probability of the state, so every gate has an inverse.',
    limitations: 'Cube moves are a finite set of discrete shuffles. Quantum gates include continuous rotations and act on complex amplitudes, including phases that have no sticker counterpart.',
    formalConnection: 'A gate is a unitary matrix: its conjugate transpose is its inverse, so it preserves the norm of every state.',
    formalMath: 'U^\\dagger U=UU^\\dagger=I',
  },
  7: {
    title: 'A steering control for the Bloch sphere',
    analogy: 'A joystick gives directional control: a small change in angle changes the path of the controlled object. The Bloch sphere makes a qubit state orientation visible in a similar way.',
    captures: 'Single-qubit gates rotate the state around axes, while the state’s orientation predicts how later gates and measurements behave.',
    limitations: 'The Bloch sphere is not a literal place where a qubit travels. It represents pure states modulo global phase; mixed states occupy its interior.',
    formalConnection: 'The polar and azimuthal angles set the orientation of a pure qubit state on the sphere.',
    formalMath: '|\\psi\\rangle=\\cos(\\theta/2)|0\\rangle+e^{i\\phi}\\sin(\\theta/2)|1\\rangle',
  },
  8: {
    title: 'Outfits from a small wardrobe',
    analogy: 'Two shirts and two pairs of trousers give four possible outfits. Each extra two-option item doubles the number of outfits, so the list of combinations grows very quickly.',
    captures: 'The state space of n qubits is built from all combinations of single-qubit basis states, so its dimension doubles with every added qubit.',
    limitations: 'An outfit is always one specific combination. A multi-qubit state can carry an amplitude for every combination at once, and entangled states cannot be described item by item.',
    formalConnection: 'Joint states live in the tensor product space, whose dimension is the product of the parts.',
    formalMath: '\\dim\\big((\\mathbb{C}^2)^{\\otimes n}\\big)=2^n',
  },
  9: {
    title: 'An action triggered by a condition',
    analogy: 'A company may take an action only when a specified financial condition is met. The trigger controls whether the action occurs.',
    captures: 'A controlled gate applies an operation to the target conditional on the control state.',
    limitations: 'A financial trigger is checked classically. A quantum control can be in superposition, so the conditional action happens coherently across branches rather than after observing the control.',
    formalConnection: 'CNOT applies X to the target when the control is |1>; CZ adds a minus sign only to the |11> component.',
    formalMath: '\\operatorname{CNOT}|c,t\\rangle=|c,t\\oplus c\\rangle',
  },
  10: {
    title: 'Pushing off a wall on skates',
    analogy: 'When you push against a wall while wearing roller skates, the wall stays put and you roll away. The effect of an action aimed at the wall shows up on you.',
    captures: 'When the target is an eigenstate of the controlled operation, the target is unchanged and the eigenphase appears on the control qubit instead.',
    limitations: 'Skating is about momentum, which is directly visible. Kickback is a relative phase on the control’s |1> branch, and it only becomes observable through later interference.',
    formalConnection: 'A controlled-U acting on an eigenstate of U moves the eigenphase onto the control’s |1> component.',
    formalMath: 'CU\\,(a|0\\rangle+b|1\\rangle)|u\\rangle=(a|0\\rangle+be^{i\\varphi}|1\\rangle)|u\\rangle',
  },
  11: {
    title: 'A private conversation in a crowded room',
    analogy: 'A conversation in a quiet room stays private. In a crowded room, small pieces of it are overheard by many people, and you can no longer gather it all back into one private exchange.',
    captures: 'Decoherence happens when a qubit becomes correlated with its environment. The relative phase information spreads out, so interference effects fade.',
    limitations: 'Nobody needs to be listening. Decoherence is a physical interaction, not observation by a person, and the information is not erased but becomes practically impossible to recover.',
    formalConnection: 'Dephasing shrinks the off-diagonal elements of the density matrix, on a timescale called T2.',
    formalMath: '\\rho_{01}(t)=\\rho_{01}(0)\\,e^{-t/T_2}',
  },
  12: {
    title: 'A message traveling through a channel',
    analogy: 'A message can arrive unchanged through a clear communication path or become distorted by the medium. The path determines how faithfully the message survives.',
    captures: 'A quantum channel describes how a state changes during transmission, storage, or interaction with an environment. Bit-flip, depolarizing, and amplitude-damping noise are all channels.',
    limitations: 'Human messages carry meaning, while a quantum channel is a precise map on density operators. The analogy does not replace complete positivity or trace preservation.',
    formalConnection: 'A channel is a completely positive, trace-preserving map written using Kraus operators.',
    formalMath: '\\mathcal{E}(\\rho)=\\sum_k K_k\\rho K_k^\\dagger',
  },
  13: {
    title: 'A choir singing in unison or in opposition',
    analogy: 'Ask a whole choir to sing at once. If everyone sings the same note, you hear one strong, clear tone. If exactly half sing it inverted, the voices cancel. One listen tells you which kind of choir you have.',
    captures: 'Deutsch-Jozsa queries every input in superposition, marks each with a phase from f(x), and uses interference so a single query separates constant from balanced functions.',
    limitations: 'You never learn individual values of f. The algorithm relies on the promise that f is constant or balanced, and a classical randomized method can guess correctly with high probability using a few queries.',
    formalConnection: 'After the final Hadamards, the amplitude of the all-zero outcome is the average of the phase signs.',
    formalMath: '\\langle 0^n|\\psi\\rangle=\\frac{1}{2^n}\\sum_x(-1)^{f(x)}',
  },
  14: {
    title: 'Clues that narrow down a hidden rule',
    analogy: 'In a memory card game, cards come in matching pairs placed by one hidden rule. Classically you flip cards until you happen to find a match. Simon’s algorithm instead hands you random clues the rule must satisfy, and a handful of clues pins it down.',
    captures: 'Each run returns a random string orthogonal to the hidden period. About n runs plus classical linear algebra recover the period.',
    limitations: 'Simon’s problem is an oracle problem built for this purpose, and its speedup is about query counts. The card game misses that the clues come from interference across all inputs at once.',
    formalConnection: 'Every measured string y satisfies a linear equation with the hidden string s.',
    formalMath: 'y\\cdot s\\equiv 0\\pmod 2',
  },
  15: {
    title: 'Finding the loop length in a repeating pattern',
    analogy: 'If a long drum loop repeats every r beats, knowing r reveals its structure. Shor’s algorithm turns factoring into finding the loop length of a repeating number pattern, then uses simple arithmetic to recover the factors.',
    captures: 'Factoring reduces to period finding. The quantum part finds the period with the QFT, and the classical part turns that period into factors.',
    limitations: 'Hearing a loop is easy; the period here hides in an exponentially long sequence. Running Shor on cryptographic sizes needs large fault-tolerant machines, and some runs give an unlucky period that requires a retry.',
    formalConnection: 'With the period r of a modulo N, a greatest common divisor often yields a nontrivial factor.',
    formalMath: 'a^r\\equiv 1\\pmod N,\\quad \\gcd(a^{r/2}\\pm1,N)',
  },
  16: {
    title: 'Checking totals without reading every entry',
    analogy: 'An auditor can check that row and column totals agree without reading every private entry. When one total disagrees, the pattern of mismatches points to the line that went wrong.',
    captures: 'Error correction measures parity checks, called syndromes, that locate errors without measuring the protected logical information.',
    limitations: 'An auditor can copy the books, but unknown quantum states cannot be copied. Quantum errors can also be phase errors or small continuous rotations, which syndrome measurement turns into discrete corrections.',
    formalConnection: 'The three-qubit bit-flip code spreads one logical qubit over three physical qubits, and parity checks such as Z1Z2 and Z2Z3 reveal which one flipped.',
    formalMath: '|\\psi_L\\rangle=\\alpha|000\\rangle+\\beta|111\\rangle',
  },
  17: {
    title: 'A matched kit and two short notes',
    analogy: 'Two friends each hold half of a matched kit prepared in advance. The sender combines an item with their half, writes down two short notes, and posts them. The receiver follows the notes to adjust their half into the original item, while the sender’s copy is used up.',
    captures: 'Teleportation moves a qubit state using a shared entangled pair plus two classical bits. The original is consumed, and nothing usable arrives before the classical message.',
    limitations: 'No matter travels, and the sender never learns the state being sent. The notes are random bits that reveal nothing about the state on their own, and they travel no faster than light.',
    formalConnection: 'One shared Bell pair and two classical bits are enough to transmit one unknown qubit state.',
    formalMath: '1\\ \\text{ebit}+2\\ \\text{cbits}\;\\Rightarrow\;1\\ \\text{qubit}',
  },
  18: {
    title: 'A forecast rather than a report',
    analogy: 'A forecast of 70 percent chance of rain does not describe one sure day. It summarizes what you know about many possible days. A density matrix similarly describes situations where you only have partial knowledge of the state.',
    captures: 'Density matrices represent mixed states, open systems, and parts of larger entangled systems, which a single state vector cannot describe.',
    limitations: 'A forecast is just a list of probabilities. A density matrix also stores coherences between states, and different mixtures can produce exactly the same density matrix.',
    formalConnection: 'A density matrix is a probability-weighted sum of pure-state projectors, with unit trace.',
    formalMath: '\\rho=\\sum_i p_i|\\psi_i\\rangle\\langle\\psi_i|,\\quad \\operatorname{Tr}\\rho=1',
  },
  19: {
    title: 'Puzzles that are hard to solve but easy to check',
    analogy: 'Some puzzles are easy to solve. Others, like a large sudoku, are hard to solve but easy to check once someone shows you an answer. A quantum computer is a new kind of solver that helps with some types of puzzles, not all of them.',
    captures: 'Complexity classes sort problems by the resources needed to solve or verify them. BQP is what quantum computers solve efficiently, and QMA is what they can verify with a quantum proof.',
    limitations: 'Puzzles feel hard or easy to people, while complexity classes are about how cost grows with input size. Quantum computers are not believed to solve NP-complete problems efficiently, and many class separations remain unproven.',
    formalConnection: 'BQP contains classical polynomial time and sits inside polynomial space.',
    formalMath: '\\mathrm{P}\\subseteq\\mathrm{BQP}\\subseteq\\mathrm{PSPACE}',
  },
  20: {
    title: 'Adjusting a shower by feel',
    analogy: 'You turn the shower knobs, feel the water, and adjust again until the temperature is right. The shower produces the water; your hand and judgement decide the next adjustment.',
    captures: 'Variational algorithms run a parameterized quantum circuit, estimate a cost from measurements, and let a classical optimizer update the parameters in a loop.',
    limitations: 'Each reading of the quantum cost is a noisy estimate from many repeated shots. The landscape can be very flat, which makes training hard, and there is no general guarantee of quantum advantage.',
    formalConnection: 'The optimizer searches for parameters that minimize the expected cost of the prepared state.',
    formalMath: '\\theta^*=\\arg\\min_\\theta\\langle\\psi(\\theta)|H|\\psi(\\theta)\\rangle',
  },
  21: {
    title: 'A prism that splits light into colours',
    analogy: 'A prism turns white light into its separate colours, showing which frequencies are present. The light was the same; the prism just presents it in a different way.',
    captures: 'The quantum Fourier transform changes basis so that periodic structure in amplitudes shows up as concentrated peaks.',
    limitations: 'A prism shows the whole spectrum at once. After a QFT, measurement returns one sample, so its value appears only inside algorithms such as phase estimation and Shor’s algorithm.',
    formalConnection: 'The QFT maps each basis state to an evenly weighted superposition with phases set by the input.',
    formalMath: '\\mathrm{QFT}|x\\rangle=\\frac{1}{\\sqrt N}\\sum_{k=0}^{N-1}e^{2\\pi ixk/N}|k\\rangle',
  },
  22: {
    title: 'Timing more and more laps',
    analogy: 'To measure a runner’s lap time precisely, time one lap, then two, then four, then eight. Longer runs reveal finer digits of the lap time.',
    captures: 'Phase estimation applies the unitary 1, 2, 4, and more times under control, so each control qubit records another binary digit of the eigenphase.',
    limitations: 'A stopwatch reads digits directly. Here the digits sit in phases that need an inverse QFT to read, the input must be an eigenstate, and the result is probabilistic unless the phase has an exact finite binary form.',
    formalConnection: 'The algorithm estimates the phase in the eigenvalue of a unitary.',
    formalMath: 'U|u\\rangle=e^{2\\pi i\\varphi}|u\\rangle',
  },
  23: {
    title: 'A flight simulator for physics',
    analogy: 'A flight simulator reproduces how an aircraft responds without flying one. A quantum computer can reproduce how a quantum system evolves, which classical computers struggle with because the state grows so quickly.',
    captures: 'Hamiltonian simulation approximates time evolution so that properties of molecules or materials can be studied on a quantum device.',
    limitations: 'A flight simulator shows the whole scene. A quantum simulation returns measurement samples of chosen observables, and it needs an efficient description of the Hamiltonian.',
    formalConnection: 'Time evolution under a Hamiltonian is a unitary that the circuit approximates.',
    formalMath: '|\\psi(t)\\rangle=e^{-iHt}|\\psi(0)\\rangle',
  },
  24: {
    title: 'A small vocabulary of physical controls',
    analogy: 'A vehicle needs only a few controls, such as steering, acceleration, and braking, but combinations of them produce many different trajectories.',
    captures: 'A universal gate set provides a compact vocabulary from which arbitrary computations can be composed or approximated.',
    limitations: 'Vehicle controls are not operators on a Hilbert space, and “universal” does not mean every circuit is short or equally easy to compile.',
    formalConnection: 'A universal set generates a dense family of unitary operations, often up to an approximation error and global phase.',
  },
  25: {
    title: 'A survey question with fixed answer boxes',
    analogy: 'A survey question comes with a fixed set of answer boxes. The question you choose decides which boxes exist, and once a box is ticked, asking the same question again gets the same tick.',
    captures: 'An observable defines the possible outcomes and their projectors. A projective measurement gives repeatable results, and the chosen basis shapes what can be learned.',
    limitations: 'Survey answers exist before the question is asked. Quantum outcomes follow the Born rule, and asking an incompatible question changes the answers to later ones.',
    formalConnection: 'An observable decomposes into eigenvalues and projectors, and the state updates to the normalized projection after an outcome.',
    formalMath: 'A=\\sum_i a_i\\Pi_i,\\quad |\\psi\\rangle\\mapsto\\frac{\\Pi_i|\\psi\\rangle}{\\sqrt{p_i}}',
  },
  26: {
    title: 'Hearing a rhythm instead of counting beats',
    analogy: 'When you listen to a drumbeat, you can tell its tempo without writing down every hit. The pattern becomes obvious once you listen for repetition.',
    captures: 'When amplitudes repeat with period r, the QFT concentrates them near multiples of N/r, which a measurement can then reveal.',
    limitations: 'Listening tells you the tempo immediately. A QFT measurement gives one random peak, and classical post-processing such as continued fractions is needed to recover the period.',
    formalConnection: 'For a periodic input, the transformed amplitudes peak at outcomes close to integer multiples of N/r.',
    formalMath: 'k\\approx j\\,\\frac{N}{r},\\quad j=0,1,\\dots,r-1',
  },
  27: {
    title: 'Clock hands turning at different speeds',
    analogy: 'A clock shows an exact time with hands that turn at different rates. Together they encode a precise value. The QFT circuit writes the input into the phases of its output qubits, each turning twice as fast as the next.',
    captures: 'The QFT factors into single-qubit states whose phases are binary fractions of the input, built with Hadamards, controlled phase rotations, and a final swap.',
    limitations: 'Clock hands move continuously and visibly. The phases here must be read through interference, and very small rotations are often dropped to give a cheaper approximate QFT.',
    formalConnection: 'The controlled rotation R_k adds a phase of 2π/2^k, supplying finer and finer binary digits.',
    formalMath: 'R_k=\\operatorname{diag}(1,e^{2\\pi i/2^k})',
  },
  28: {
    title: 'Reading a measurement off gears',
    analogy: 'Imagine a set of gears where each turns twice as fast as the previous one. Where each gear points tells you one digit of an angle, and reading all of them together gives the angle precisely.',
    captures: 'The control register picks up phases that double from qubit to qubit, and the inverse QFT converts them into a binary estimate of the eigenphase.',
    limitations: 'Gear positions can be read directly. Phases cannot, so the inverse QFT is required, and when the phase is not an exact t-bit fraction the best estimate appears with high but not certain probability.',
    formalConnection: 'The inverse QFT turns the phase pattern on the control register into a computational basis estimate of φ.',
    formalMath: '\\frac{1}{2^{t/2}}\\sum_{k}e^{2\\pi i\\varphi k}|k\\rangle\\xrightarrow{\\mathrm{QFT}^{-1}}|\\tilde\\varphi\\rangle',
  },
  29: {
    title: 'Walking a curve in small steps',
    analogy: 'To walk a smooth curve, you can alternate tiny steps forward with tiny turns. The smaller the pieces, the closer your zigzag path gets to the curve. Turning then stepping is not quite the same as stepping then turning, and that difference is the error.',
    captures: 'Trotterization splits evolution under a sum of terms into short alternating pieces. The approximation improves as the steps get smaller.',
    limitations: 'Walking is classical motion in space. Here the pieces are unitaries, and the error depends on how strongly the Hamiltonian terms fail to commute.',
    formalConnection: 'Alternating short evolutions approximates the full evolution, with error controlled by the commutator [A,B]=AB-BA.',
    formalMath: 'e^{-i(A+B)t}\\approx\\big(e^{-iAt/n}e^{-iBt/n}\\big)^n',
  },
  30: {
    title: 'Searching for the valley floor',
    analogy: 'You are searching for the lowest point of a valley. Every spot you test is at least as high as the true floor, so the lowest reading so far is always an upper bound on the depth.',
    captures: 'VQE adjusts a parameterized circuit to lower the measured energy, and the variational principle guarantees every estimate is at or above the true ground-state energy.',
    limitations: 'Real hills do not hide their shape. The circuit family may not reach the true floor, energy estimates are noisy, and measuring many Hamiltonian terms can be expensive.',
    formalConnection: 'The energy of any trial state is bounded below by the ground-state energy.',
    formalMath: 'E(\\theta)=\\langle\\psi(\\theta)|H|\\psi(\\theta)\\rangle\\ge E_0',
  },
  31: {
    title: 'Alternating between favourites and exploring',
    analogy: 'Looking for the best café in a city, you alternate between steps that favour places you already rate highly and steps that mix things up to explore other streets. How many rounds you take and how long each lasts are dials you tune.',
    captures: 'QAOA alternates a cost layer and a mixer layer, with angles chosen by a classical optimizer, for a fixed number of rounds p.',
    limitations: 'A café search is a classical walk. QAOA moves amplitudes that interfere, and its performance guarantees are limited for small p.',
    formalConnection: 'The state is built by alternating cost and mixer unitaries applied to the uniform superposition.',
    formalMath: '|\\gamma,\\beta\\rangle=\\prod_{j=1}^{p}e^{-i\\beta_jH_M}e^{-i\\gamma_jH_C}|+\\rangle^{\\otimes n}',
  },
  32: {
    title: 'Finding a low-cost route',
    analogy: 'Route planning searches for a low-cost path through many possibilities. A useful method should avoid getting trapped by poor local choices.',
    captures: 'Optimization problems can be expressed through a cost landscape, which motivates methods that balance exploration and movement toward low-energy solutions.',
    limitations: 'A classical route planner is not a quantum annealer. Annealing follows a time-dependent Hamiltonian and real devices may be open, noisy, and hardware-specific.',
    formalConnection: 'The schedule interpolates between an easy initial Hamiltonian and a problem Hamiltonian, ideally tracking a low-energy state.',
    formalMath: 'H(s)=(1-s)H_0+sH_P,\\quad 0\\leq s\\leq 1',
  },
  33: {
    title: 'Carrying a full cup slowly',
    analogy: 'Carry a full cup of coffee slowly and it stays in the cup. Rush and it spills. The narrower the cup, the slower you need to go.',
    captures: 'Adiabatic computation changes the Hamiltonian slowly enough for the system to stay in its ground state, and the required time depends on the smallest energy gap.',
    limitations: 'Coffee spills because of classical motion. In quantum evolution, leaving the ground state means transitions to excited states, and real devices also suffer noise and finite temperature.',
    formalConnection: 'In its simplest form, the total evolution time must be large compared with the inverse square of the minimum gap.',
    formalMath: 'T\\gg\\frac{1}{\\Delta_{\\min}^2}',
  },
  34: {
    title: 'Listening for beats against a reference',
    analogy: 'To learn a tuning fork’s pitch, you do not take it apart. You strike it next to a reference and listen to the beat between them. The information shows up in the comparison, not in the fork.',
    captures: 'Algorithms use phase kickback to write oracle or eigenvalue information into the control register, then use interference to read it out.',
    limitations: 'Beats are classical sound waves you can hear continuously. A single quantum run returns one measurement sample, so the phase must be designed to produce a useful outcome.',
    formalConnection: 'With the target in |->, an oracle that flips the target writes f(x) as a phase on the input register.',
    formalMath: 'U_f|x\\rangle|-\\rangle=(-1)^{f(x)}|x\\rangle|-\\rangle',
  },
  35: {
    title: 'A rowing crew in and out of sync',
    analogy: 'When a rowing crew pulls in sync, the boat surges forward. When the timing is off, the strokes work against each other. Coaching the timing matters as much as the strength.',
    captures: 'Quantum algorithms choreograph phases so that paths to wrong answers cancel and paths to useful answers reinforce.',
    limitations: 'Rowers apply real forces in space. Amplitudes are complex numbers that add before being squared into probabilities, and they can cancel completely.',
    formalConnection: 'The probability of an outcome is the squared magnitude of the sum of amplitudes over every path leading to it.',
    formalMath: 'P(x)=\\Big|\\sum_{\\text{paths}}a_{\\text{path}}\\Big|^2',
  },
  36: {
    title: 'A recipe is not a photocopier',
    analogy: 'A recipe can be copied and followed, but copying a dish that is already prepared requires learning what is in it and may change the original. An unknown quantum state is more constrained than an ordinary file.',
    captures: 'The no-cloning theorem separates copying a known preparation procedure from making a perfect second copy of an arbitrary unknown state.',
    limitations: 'A recipe is classical information. Quantum states can be transferred and correlated, but the analogy does not prove the theorem.',
    formalConnection: 'Linearity fixes the action of a proposed copier on superpositions and creates the contradiction.',
    formalMath: 'U|\\psi\\rangle|0\\rangle\\ne|\\psi\\rangle|\\psi\\rangle',
  },
  37: {
    title: 'Turning up one radio station',
    analogy: 'Imagine a crowded dial where one station matters. A filter can combine signals so the desired station grows while unrelated frequencies cancel.',
    captures: 'Grover iterations use phase marking and diffusion to rotate amplitude toward marked solutions.',
    limitations: 'A radio filter is classical and does not provide a search speedup. Grover also needs a reversible oracle and careful iteration count.',
    formalConnection: 'The oracle and diffusion operator form a rotation in the span of marked and unmarked states.',
    formalMath: 'G=(2|s\\rangle\\langle s|-I)O',
  },
  38: {
    title: 'A tamper-evident seal',
    analogy: 'A package can arrive with a seal that is not guaranteed to prevent every attack, but a broken or statistically unusual seal reveals that the channel needs investigation.',
    captures: 'BB84 uses basis choices and sampled error rates to detect disturbance before accepting key material.',
    limitations: 'A seal is not a security proof. BB84 also needs authentication, privacy amplification, finite-key analysis, and trusted implementation assumptions.',
    formalConnection: 'Incompatible bases make some intercept-and-resend actions produce detectable errors.',
    formalMath: '\\Pr(\\mathrm{error})=\\frac{1}{4}',
  },
  39: {
    title: 'Different vehicles, different roads',
    analogy: 'A city bus, a racing bicycle, and a train can all move people, but their speed, routes, maintenance, and capacity tradeoffs differ.',
    captures: 'Quantum platforms can run related abstract circuits while differing in control, connectivity, coherence, readout, and scaling.',
    limitations: 'The vehicle comparison does not capture quantum fidelity or error correction. Platform choices must be measured for a concrete workload.',
    formalConnection: 'The abstract unitary model is compiled into platform-specific operations and noise processes.',
  },
  40: {
    title: 'Compiling a recipe for a constrained kitchen',
    analogy: 'A recipe may describe any ingredients and order, while a particular kitchen has limited tools, workspace, and timing. The cook must rewrite the recipe without changing the intended dish.',
    captures: 'Quantum compilation decomposes, routes, schedules, and optimizes an abstract circuit for a real device.',
    limitations: 'A kitchen does not have unitary approximation error or qubit connectivity. The analogy explains constraints, not the mathematics.',
    formalConnection: 'The compiler approximates a target unitary with native gates while controlling depth and hardware cost.',
    formalMath: 'U_{\\mathrm{target}}\\approx G_m\\cdots G_1',
  },
};
