export type DemoOp = {
  gateId: string;
  targetQubit: number;
  controlQubit?: number;
};

export type LessonQuiz = {
  prompt: string;
  options: string[];
  answer: 'a' | 'b' | 'c' | 'd';
  explanation: string;
};

export type LessonMeta = {
  id: number;
  title: string;
  slug: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  stage: string;
  prerequisites: number[];
  objective: string;
  xp: number;
  allowedGates: string[];
  challengeType: 'circuit' | 'read';
  upcoming?: boolean;
  demoOps?: DemoOp[];
  quiz?: LessonQuiz;
};

const QUIZZES: Record<number, LessonQuiz> = {
  1: {
    prompt: 'What does a Hadamard gate do to |0⟩?',
    options: ['It leaves it unchanged', 'It turns it into |1⟩', 'It creates an equal superposition of |0⟩ and |1⟩', 'It measures it instantly'],
    answer: 'c',
    explanation: 'A Hadamard gate maps |0⟩ to an equal superposition of the two computational basis states.',
  },
  2: {
    prompt: 'Which statement best describes superposition?',
    options: ['A state that is definitely one outcome', 'A linear combination of basis states with amplitudes', 'A state that has no measurement uncertainty', 'A classical random bit'],
    answer: 'b',
    explanation: 'Superposition means the state is a coherent linear combination of basis states, not just a classical mixture.',
  },
  3: {
    prompt: 'What does measurement do in the simple picture of this course?',
    options: ['It creates new amplitudes', 'It converts quantum amplitudes into a classical outcome', 'It makes gates unitary', 'It removes all phase information forever'],
    answer: 'b',
    explanation: 'Measurement turns the quantum state into a concrete classical result according to the amplitudes.',
  },
  4: {
    prompt: 'What is entanglement?',
    options: ['A type of classical randomness', 'A joint state that cannot be written as a product of local states', 'A measurement error', 'A gate that always flips a qubit'],
    answer: 'b',
    explanation: 'Entangled states are non-factorizable: the joint state cannot be separated into independent local states.',
  },
  5: {
    prompt: 'Interference is mainly about which quantity?',
    options: ['The number of qubits', 'The relative phase of amplitudes', 'The speed of the gate', 'The amount of classical memory'],
    answer: 'b',
    explanation: 'Interference depends on the relative phase between amplitudes, which can make them reinforce or cancel.',
  },
  6: {
    prompt: 'Why must an ideal quantum gate be unitary?',
    options: ['Because it must be random', 'Because it must preserve normalization and reversibility', 'Because it can only act on one qubit', 'Because it cannot be represented as a matrix'],
    answer: 'b',
    explanation: 'Unitary gates preserve the total probability and are reversible before measurement.',
  },
  7: {
    prompt: 'What does the Bloch sphere represent?',
    options: ['The physical shape of a qubit', 'The geometry of a single-qubit pure state', 'The circuit depth', 'The classical bit value'],
    answer: 'b',
    explanation: 'The Bloch sphere is a geometric view of the state of a single qubit.',
  },
  8: {
    prompt: 'What grows exponentially when you add more qubits?',
    options: ['The number of gates in a circuit', 'The dimension of the state space', 'The strength of measurement', 'The size of a classical register'],
    answer: 'b',
    explanation: 'A system of n qubits lives in a Hilbert space of dimension 2^n.',
  },
  9: {
    prompt: 'What is a quantum circuit mainly used for?',
    options: ['To store classical data', 'To describe a sequence of gate operations', 'To create random noise', 'To replace measurement'],
    answer: 'b',
    explanation: 'A circuit is a visual and mathematical way to describe a sequence of quantum operations.',
  },
  10: {
    prompt: 'Phase kickback is most closely related to what effect?',
    options: ['A classical OR operation', 'A phase change that appears on the control qubit', 'A measurement collapse', 'A reset operation'],
    answer: 'b',
    explanation: 'Phase kickback transfers phase information into the control qubit through a controlled operation.',
  },
  11: {
    prompt: 'What does decoherence describe?',
    options: ['The loss of phase information due to environmental interaction', 'The creation of a new qubit', 'The exact reversal of a circuit', 'The equalization of all measurement outcomes'],
    answer: 'a',
    explanation: 'Decoherence is the loss of coherence caused by interaction with the environment.',
  },
  12: {
    prompt: 'What is a common consequence of quantum noise?',
    options: ['Perfect gate reversibility', 'Logical errors in the computation', 'No change in measurement statistics', 'A guaranteed entangled state'],
    answer: 'b',
    explanation: 'Noise can cause errors that change the intended computation.',
  },
  13: {
    prompt: 'What is the main goal of Deutsch-Jozsa?',
    options: ['To solve factoring', 'To distinguish constant from balanced functions with one query', 'To simulate Hamiltonians', 'To create superposition only'],
    answer: 'b',
    explanation: 'Deutsch-Jozsa uses quantum parallelism to decide a property of a function more efficiently than classical methods in the idealized case.',
  },
  14: {
    prompt: "What does Simon's algorithm exploit?",
    options: ['A classical sorting trick', 'An unknown periodicity hidden in a function', 'A fixed gate sequence', 'Only single-qubit gates'],
    answer: 'b',
    explanation: "Simon's algorithm uses quantum interference to reveal a hidden period in a black-box function.",
  },
  15: {
    prompt: "Shor's algorithm is famous for its use in which task?",
    options: ['Sorting numbers', 'Factoring integers', 'Searching a database', 'Sampling random states'],
    answer: 'b',
    explanation: "Shor's algorithm is best known for factoring integers efficiently using period finding.",
  },
  16: {
    prompt: 'Why do we use error correction in quantum computing?',
    options: ['To avoid all measurement', 'To protect logical qubits from noise and decoherence', 'To remove all entanglement', 'To simplify gate sets'],
    answer: 'b',
    explanation: 'Quantum error correction preserves fragile logical information despite errors.',
  },
  17: {
    prompt: 'What is quantum teleportation mainly using?',
    options: ['A classical memory channel only', 'Entanglement plus classical communication', 'Only unitary gates', 'Only measurement without entanglement'],
    answer: 'b',
    explanation: 'Teleportation uses entanglement and classical communication to transfer a state.',
  },
  18: {
    prompt: 'What do density matrices describe?',
    options: ['Only pure states', 'Mixed states and open systems', 'Only classical bits', 'Only one-qubit circuits'],
    answer: 'b',
    explanation: 'Density matrices describe statistical mixtures and open-system states.',
  },
  19: {
    prompt: 'What does BQP refer to?',
    options: ['A classical search algorithm', 'The class of problems efficiently solvable by a quantum computer', 'A noise model', 'A measurement basis'],
    answer: 'b',
    explanation: 'BQP is the complexity class for problems efficiently solvable by a quantum computer.',
  },
  20: {
    prompt: 'What is a variational algorithm mainly doing?',
    options: ['Ignoring classical compute', 'Optimizing parameters in a hybrid quantum-classical loop', 'Removing all measurements', 'Only using one gate'],
    answer: 'b',
    explanation: 'Variational methods use a quantum circuit and a classical optimizer together to find good parameters.',
  },
  21: {
    prompt: 'What is the quantum Fourier transform best known for?',
    options: ['Reversing a qubit', 'Re-expressing amplitudes in a frequency basis', 'Removing all phase', 'Replacing measurement'],
    answer: 'b',
    explanation: 'The QFT reshapes amplitudes into a frequency-like basis that is useful for period finding and phase estimation.',
  },
  22: {
    prompt: 'Phase estimation is mainly used to find what?',
    options: ['A random bit', 'The eigenvalue of a unitary operator', 'A classical register size', 'The number of qubits in memory'],
    answer: 'b',
    explanation: 'Phase estimation extracts an eigenvalue, often encoded as an angle, from a unitary operator.',
  },
  23: {
    prompt: 'Hamiltonian simulation is about modeling what?',
    options: ['Only classical sorting', 'The time evolution of a physical system', 'A static webpage', 'Only single-gate circuits'],
    answer: 'b',
    explanation: 'Hamiltonian simulation studies how a quantum system evolves under a Hamiltonian over time.',
  },
};

export function getLessonQuiz(lessonId: number): LessonQuiz | undefined {
  return QUIZZES[lessonId];
}

export const LESSONS: LessonMeta[] = [
  {
    id: 1,
    title: 'Birth of Quantum Information',
    slug: 'birth-of-quantum-information',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [],
    objective: 'Understand why a qubit is more expressive than a classical bit.',
    xp: 100,
    allowedGates: ['H'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(1),
  },
  {
    id: 2,
    title: 'Superposition',
    slug: 'superposition',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1],
    objective: 'Explain superposition as linear combination in Hilbert space.',
    xp: 100,
    allowedGates: ['H', 'X'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(2),
  },
  {
    id: 3,
    title: 'Measurement',
    slug: 'measurement',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2],
    objective: 'Understand measurement as the bridge from quantum amplitudes to classical outcomes.',
    xp: 120,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(3),
  },
  {
    id: 4,
    title: 'Entanglement',
    slug: 'entanglement',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 3],
    objective: 'See entanglement as non-factorizable joint state structure.',
    xp: 150,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
    quiz: getLessonQuiz(4),
  },
  {
    id: 5,
    title: 'Interference',
    slug: 'interference',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 3],
    objective: 'Understand how relative phase makes amplitudes reinforce or cancel.',
    xp: 150,
    allowedGates: ['H', 'X', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(5),
  },
  // ── Upcoming ───────────────────────────────────────────────────────────
  {
    id: 6,
    title: 'Quantum Gates & Unitarity',
    slug: 'quantum-gates-unitarity',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2],
    objective: 'Understand why all quantum gates must be unitary and reversible.',
    xp: 150,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S', 'T'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(6),
  },
  {
    id: 7,
    title: 'The Bloch Sphere',
    slug: 'bloch-sphere',
    difficulty: 'beginner',
    stage: 'foundation',
    prerequisites: [1, 2, 5],
    objective: 'Map single-qubit state space to a geometric sphere.',
    xp: 150,
    allowedGates: ['H', 'X', 'Y', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
  },
  {
    id: 8,
    title: 'Multi-Qubit Systems',
    slug: 'multi-qubit-systems',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [1, 2, 3, 4],
    objective: 'Describe joint states of n qubits using tensor products.',
    xp: 200,
    allowedGates: ['H', 'X', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
    ],
    quiz: getLessonQuiz(8),
  },
  {
    id: 9,
    title: 'Quantum Circuits',
    slug: 'quantum-circuits',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [6, 8],
    objective: 'Read and build quantum circuits using the gate-wire formalism.',
    xp: 200,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
    ],
    quiz: getLessonQuiz(9),
  },
  {
    id: 10,
    title: 'Phase Kickback',
    slug: 'phase-kickback',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [4, 5, 6],
    objective: 'Derive how a controlled gate transfers phase to the control qubit.',
    xp: 200,
    allowedGates: ['H', 'X', 'Z', 'S', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
      { gateId: 'H', targetQubit: 1 },
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(10),
  },
  {
    id: 11,
    title: 'Decoherence',
    slug: 'decoherence',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [5, 9, 10],
    objective: 'Understand decoherence as loss of phase information caused by environmental coupling.',
    xp: 250,
    allowedGates: ['H', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(11),
  },
  {
    id: 12,
    title: 'Quantum Noise and Errors',
    slug: 'quantum-noise-and-errors',
    difficulty: 'intermediate',
    stage: 'core',
    prerequisites: [5, 9, 10],
    objective: 'Model common quantum noise processes and how they produce logical errors.',
    xp: 250,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(12),
  },
  {
    id: 13,
    title: "Deutsch-Jozsa Algorithm",
    slug: 'deutsch-jozsa',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [5, 9, 10],
    objective: 'Prove that one quantum query distinguishes constant from balanced functions.',
    xp: 250,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'X', targetQubit: 1 },
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'H', targetQubit: 1 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(13),
  },
  {
    id: 14,
    title: "Simon's Algorithm",
    slug: 'simons-algorithm',
    difficulty: 'intermediate',
    stage: 'algorithms',
    prerequisites: [9, 11, 13],
    objective: 'Find hidden periods exponentially faster than any classical algorithm.',
    xp: 300,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(14),
  },
  {
    id: 15,
    title: "Shor's Algorithm",
    slug: 'shors-algorithm',
    difficulty: 'advanced',
    stage: 'algorithms',
    prerequisites: [11, 14],
    objective: 'Factor integers in polynomial time using quantum period finding.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(15),
  },
  {
    id: 16,
    title: 'Quantum Error Correction',
    slug: 'quantum-error-correction',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [8, 9, 4],
    objective: 'Encode logical qubits to protect against decoherence and gate errors.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(16),
  },
  {
    id: 17,
    title: 'Quantum Teleportation',
    slug: 'quantum-teleportation',
    difficulty: 'intermediate',
    stage: 'advanced',
    prerequisites: [4, 9, 3],
    objective: 'Transmit an arbitrary qubit state using entanglement and classical bits.',
    xp: 300,
    allowedGates: ['H', 'X', 'Z', 'CNOT'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'CNOT', targetQubit: 1, controlQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(17),
  },
  {
    id: 18,
    title: 'Density Matrices',
    slug: 'density-matrices',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [7, 8, 3],
    objective: 'Represent mixed states and open quantum systems with density operators.',
    xp: 350,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'Z', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(18),
  },
  {
    id: 19,
    title: 'Quantum Complexity Theory',
    slug: 'quantum-complexity',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [12, 15],
    objective: 'Understand BQP, QMA, and where quantum advantage actually lives.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z'],
    challengeType: 'read',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'X', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(19),
  },
  {
    id: 20,
    title: 'Variational Quantum Algorithms',
    slug: 'variational-quantum-algorithms',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [9, 11, 18],
    objective: 'Design hybrid classical-quantum loops for near-term quantum hardware.',
    xp: 400,
    allowedGates: ['H', 'X', 'Z', 'S'],
    challengeType: 'circuit',
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
      { gateId: 'H', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(20),
  },
  {
    id: 21,
    title: 'Quantum Fourier Transform',
    slug: 'quantum-fourier-transform',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [9, 15],
    objective: 'Understand why the quantum Fourier transform is central to many quantum algorithms.',
    xp: 450,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    upcoming: true,
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(21),
  },
  {
    id: 22,
    title: 'Phase Estimation',
    slug: 'phase-estimation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [15, 21],
    objective: 'See how phase estimation turns eigenvalue information into useful algorithmic output.',
    xp: 450,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    upcoming: true,
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(22),
  },
  {
    id: 23,
    title: 'Hamiltonian Simulation',
    slug: 'hamiltonian-simulation',
    difficulty: 'advanced',
    stage: 'advanced',
    prerequisites: [16, 20],
    objective: 'Understand how quantum computers simulate the dynamics of physical systems.',
    xp: 500,
    allowedGates: ['H', 'S', 'CNOT'],
    challengeType: 'read',
    upcoming: true,
    demoOps: [
      { gateId: 'H', targetQubit: 0 },
      { gateId: 'S', targetQubit: 0 },
    ],
    quiz: getLessonQuiz(23),
  },
];

export function getLessonBySlug(slug: string): LessonMeta | undefined {
  return LESSONS.find((l) => l.slug === slug);
}

export function getLessonById(id: number): LessonMeta | undefined {
  return LESSONS.find((l) => l.id === id);
}
