export type LessonVisualMode =
  | 'amplitude'
  | 'phase'
  | 'measurement'
  | 'entanglement'
  | 'noise'
  | 'circuit'
  | 'algorithm'
  | 'resource'
  | 'hardware'
  | 'protocol';

export type LessonVisual = {
  mode: LessonVisualMode;
  title: string;
  description: string;
  focus: string;
  ideal: string;
  reality: string;
};

export const LESSON_VISUALS: Record<number, LessonVisual> = {
  1: { mode: 'amplitude', title: 'A qubit carries amplitude and phase', description: 'Watch a basis state open into two complex amplitude components.', focus: 'The bar height shows magnitude; the color pulse marks phase information.', ideal: 'Exact state-vector picture', reality: 'A physical qubit needs preparation and calibrated control' },
  2: { mode: 'amplitude', title: 'Superposition is coherent, not merely random', description: 'Two balanced components can still carry different relative phase.', focus: 'Equal bars do not mean equal quantum states.', ideal: 'Coherent linear combination', reality: 'A classical mixture loses the phase relationship' },
  3: { mode: 'measurement', title: 'Probabilities become samples', description: 'The ideal distribution stays fixed while finite-shot counts fluctuate around it.', focus: 'One shot is an outcome; the distribution needs repeated shots.', ideal: 'Born probabilities', reality: 'Finite samples plus hardware readout error' },
  4: { mode: 'entanglement', title: 'The joint state carries the correlation', description: 'The correlated outcomes stay linked even though each single-qubit view is balanced.', focus: '00 and 11 are supported; 01 and 10 are suppressed in this Bell state.', ideal: 'Two-qubit Bell state', reality: 'Hardware correlations are finite-shot and noise-sensitive' },
  5: { mode: 'phase', title: 'Interference turns phase into outcome', description: 'Two paths recombine: matching phase reinforces, opposite phase cancels.', focus: 'The final basis change makes relative phase measurable.', ideal: 'Coherent path amplitudes', reality: 'Control errors reduce contrast' },
  6: { mode: 'circuit', title: 'Unitary gates can be undone', description: 'A reversible operation moves the state forward, then returns it to its input.', focus: 'The ideal path closes exactly because normalization is preserved.', ideal: 'Reversible matrix evolution', reality: 'Physical gates are approximations with error' },
  7: { mode: 'phase', title: 'A phase rotation moves around the Bloch sphere', description: 'The state can change direction while computational-basis populations stay fixed.', focus: 'Geometry exposes information probability bars hide.', ideal: 'Pure single-qubit geometry', reality: 'Noise shortens or distorts the Bloch vector' },
  8: { mode: 'entanglement', title: 'More qubits create a larger joint space', description: 'Independent local superpositions populate four basis states without creating entanglement.', focus: 'State-space dimension grows before correlations become nonlocal.', ideal: 'Tensor-product state', reality: 'Control and readout complexity also grow' },
  9: { mode: 'circuit', title: 'A circuit is an ordered transformation', description: 'Each gate changes the state passed to the next gate in the wire.', focus: 'Read operations left to right and keep qubit order explicit.', ideal: 'Exact gate sequence', reality: 'Compilation can rewrite the physical sequence' },
  10: { mode: 'phase', title: 'A controlled gate can kick phase back', description: 'The target returns to its eigenstate while the control records the eigenvalue as phase.', focus: 'A visible target flip is not required for information to move.', ideal: 'Controlled-unitary mechanism', reality: 'Controlled gates need calibrated interactions' },
  11: { mode: 'noise', title: 'Decoherence erases ensemble coherence', description: 'A deterministic phase flip is contrasted with a channel that gradually removes off-diagonal information.', focus: 'One fixed error is not the same thing as a stochastic environment.', ideal: 'Coherent comparison', reality: 'Relaxation and dephasing vary across devices and time' },
  12: { mode: 'noise', title: 'Noise is a distribution of error events', description: 'An error channel mixes possible outcomes instead of applying one known gate every time.', focus: 'The noise lens is illustrative; it is not injected into the circuit engine.', ideal: 'Named error channel', reality: 'Noise depends on device, gate, time, and measurement' },
  13: { mode: 'algorithm', title: 'Interference separates a promise case', description: 'A phase pattern from the oracle is decoded into a constant or balanced answer.', focus: 'The speedup claim depends on the promise and oracle model.', ideal: 'Two-qubit teaching instance', reality: 'Larger oracles have real construction cost' },
  14: { mode: 'algorithm', title: 'Samples become linear constraints', description: 'A toy hidden relationship produces a repeatable interference pattern.', focus: 'Simon requires repeated samples and classical linear algebra.', ideal: 'Mechanism scaffold', reality: 'The full algorithm needs larger registers and an oracle' },
  15: { mode: 'algorithm', title: 'Period finding is the useful core', description: 'A small phase pattern stands in for the interference stage of period finding.', focus: 'This does not factor an integer or implement modular exponentiation.', ideal: 'Conceptual period-finding picture', reality: 'Resource cost grows with arithmetic and precision' },
  16: { mode: 'protocol', title: 'Redundancy creates a syndrome', description: 'Three physical bits can reveal one bit-flip location without reading the logical value.', focus: 'The syndrome identifies an error; it is not the encoded message.', ideal: 'Repetition-code table', reality: 'Quantum codes also face phase errors and measurement overhead' },
  17: { mode: 'protocol', title: 'Teleportation needs a classical message', description: 'An entangled resource and two classical bits connect the input to the receiver correction.', focus: 'The state is not copied and the protocol is not complete without feed-forward.', ideal: 'Unitary skeleton plus classical branch', reality: 'Measurement, latency, and conditional gates matter' },
  18: { mode: 'noise', title: 'Mixedness removes state-vector certainty', description: 'Off-diagonal coherence fades while diagonal populations can remain unchanged.', focus: 'The same Z-basis probabilities can hide different quantum states.', ideal: 'Density-matrix comparison', reality: 'The current builder stores pure state vectors only' },
  19: { mode: 'resource', title: 'Complexity is about scaling', description: 'Qubit count, depth, samples, and classical work grow as separate resource axes.', focus: 'A small demo cannot establish an asymptotic advantage.', ideal: 'Abstract resource model', reality: 'Architecture and error correction add overhead' },
  20: { mode: 'algorithm', title: 'Variational algorithms close a feedback loop', description: 'Parameters are prepared, measured, and sent back to a classical optimizer.', focus: 'The loop trades circuit depth for repeated noisy evaluations.', ideal: 'Parameterized objective loop', reality: 'Shot noise and hardware noise shape the landscape' },
  21: { mode: 'phase', title: 'The Fourier transform reorganizes phase', description: 'Periodic phase structure becomes concentrated in a different basis.', focus: 'The useful signal is a pattern across amplitudes, not a single bar.', ideal: 'Finite-register Fourier picture', reality: 'Precision and controlled rotations cost resources' },
  22: { mode: 'phase', title: 'Phase estimation turns angle into bits', description: 'Controlled powers of a unitary write phase information onto a readout register.', focus: 'More precision means more qubits, depth, and sensitivity.', ideal: 'Phase-to-bits mechanism', reality: 'Sampling and gate errors limit precision' },
  23: { mode: 'resource', title: 'Simulation trades approximation for depth', description: 'Shorter formulas are cheaper; finer approximations use more operations.', focus: 'The best approximation is not automatically the deepest one.', ideal: 'Hamiltonian resource tradeoff', reality: 'Hardware noise competes with formula error' },
  24: { mode: 'circuit', title: 'Universal sets compose from simple pieces', description: 'A small native alphabet can approximate much richer operations when composed.', focus: 'Universality says what can be built, not how cheaply.', ideal: 'Gate-set composition', reality: 'Approximation and compilation consume depth' },
  25: { mode: 'measurement', title: 'Measurement depends on the question asked', description: 'Changing basis changes which property becomes a classical outcome.', focus: 'A measurement is an observable and a basis, not just a screenshot.', ideal: 'Projective measurement picture', reality: 'Readout has finite sampling and calibration error' },
  26: { mode: 'phase', title: 'QFT spreads and recombines phase', description: 'Rotations and controlled phases build a structured change of basis.', focus: 'The QFT is a unitary transform, not a magic frequency detector.', ideal: 'Small-register QFT structure', reality: 'Gate count and approximation matter' },
  27: { mode: 'circuit', title: 'A QFT circuit has a real gate cost', description: 'Hadamards, controlled rotations, and swaps appear as a concrete decomposition.', focus: 'The diagram exposes depth and connectivity requirements.', ideal: 'Exact decomposition for a small register', reality: 'Transpilation may add routing and native gates' },
  28: { mode: 'phase', title: 'Precision is a resource', description: 'Narrower phase bins require a longer readout register and more controlled work.', focus: 'A sharper estimate is not free.', ideal: 'Finite-bit phase estimate', reality: 'Noise blurs the estimate' },
  29: { mode: 'resource', title: 'Approximation error meets hardware error', description: 'Increasing steps can reduce formula error while increasing circuit exposure.', focus: 'Look for the useful middle ground, not a maximum step count.', ideal: 'Trotter-style tradeoff', reality: 'Device noise adds a second error curve' },
  30: { mode: 'algorithm', title: 'VQE is an experiment loop', description: 'A classical optimizer proposes parameters and the quantum circuit estimates an energy.', focus: 'Measurement cost is part of the algorithm.', ideal: 'Expectation-value workflow', reality: 'Shots, noise, and ansatz choice affect convergence' },
  31: { mode: 'algorithm', title: 'QAOA alternates two operators', description: 'Cost and mixer layers reshape amplitudes as parameters change.', focus: 'Performance depends on the problem, depth, optimizer, and sampling.', ideal: 'Parameterized alternating layers', reality: 'Deeper circuits can be harder to execute' },
  32: { mode: 'resource', title: 'Annealing follows an energy landscape', description: 'The schedule moves from an easy Hamiltonian toward a problem Hamiltonian.', focus: 'The minimum gap controls how demanding the schedule can be.', ideal: 'Adiabatic path sketch', reality: 'Thermal effects and control errors can cause transitions' },
  33: { mode: 'resource', title: 'Runtime and gap are linked', description: 'A shrinking energy gap makes an adiabatic path harder to follow.', focus: 'Qubit count alone does not describe the resource requirement.', ideal: 'Gap-limited schedule', reality: 'Open-system dynamics complicate the path' },
  34: { mode: 'phase', title: 'Kickback is phase information in motion', description: 'The target eigenvalue changes the control interference pattern.', focus: 'The useful signal appears after the final basis change.', ideal: 'Eigenphase mechanism', reality: 'Controlled operations are hardware-sensitive' },
  35: { mode: 'phase', title: 'Amplitude and phase work together', description: 'The same magnitudes can produce different outcomes after recombination.', focus: 'Probability snapshots are incomplete without phase.', ideal: 'Interference geometry', reality: 'Noise reduces coherent contrast' },
  36: { mode: 'protocol', title: 'Unknown quantum states cannot be copied', description: 'One input cannot branch into two independent perfect copies while preserving every possible state.', focus: 'Classical copying works because classical states are distinguishable.', ideal: 'No-cloning argument', reality: 'Approximate copying has a measurable fidelity tradeoff' },
  37: { mode: 'algorithm', title: 'Grover amplifies a marked subspace', description: 'Oracle and diffusion steps rotate amplitude toward marked states.', focus: 'The quadratic query claim assumes an oracle and repeated measurement.', ideal: 'Amplitude amplification', reality: 'Oracle construction and noise still cost resources' },
  38: { mode: 'protocol', title: 'Basis mismatch reveals disturbance', description: 'Alice and Bob compare a sample of compatible bases to estimate an error rate.', focus: 'Security depends on assumptions, sampling, authentication, and privacy amplification.', ideal: 'BB84 teaching protocol', reality: 'A circuit is not a production security proof' },
  39: { mode: 'hardware', title: 'Hardware platforms trade different strengths', description: 'Connectivity, control, coherence, speed, and readout form a multidimensional engineering tradeoff.', focus: 'There is no single hardware metric that settles usefulness.', ideal: 'Platform comparison', reality: 'Calibration and availability change over time' },
  40: { mode: 'hardware', title: 'Compilation makes the hardware contract visible', description: 'An abstract circuit becomes native gates arranged for a device topology.', focus: 'The output can be longer while still implementing the same logical intent.', ideal: 'Logical-to-native mapping', reality: 'Routing, scheduling, and calibration add cost' },
};

export function getLessonVisual(lessonId: number): LessonVisual {
  return LESSON_VISUALS[lessonId] ?? LESSON_VISUALS[1];
}