#!/usr/bin/env python3
"""Extract raw lesson text from the ReportLab-generated QCML PDFs.

This parser is intentionally lightweight and uses only the Python standard
library so the repo can be processed without external PDF dependencies.
It is tailored to the current PDFs, which store one lesson per page with
ASCII85 + Flate compressed content streams generated by ReportLab.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import zlib
from pathlib import Path


PDF_DIR = Path("website/public/source-pdfs")
OUT_DIR = Path("artifacts")
META_DIR = Path("_metadata/source-context")

PDF_ORDER = [
    "quantum_midway_lessons_1_5.pdf",
    "quantum_midway_lessons_6_10.pdf",
    "quantum_midway_lessons_11_15.pdf",
    "quantum_midway_lessons_16_20.pdf",
    "quantum_midway_lessons_21_25.pdf",
    "quantum_midway_lessons_26_30.pdf",
    "quantum_midway_lessons_31_35.pdf",
]

ANALOGY_PDF = "quantum_analogy_master_detailed.pdf"


def decode_streams(pdf_path: Path) -> list[str]:
    raw = pdf_path.read_bytes().decode("latin1", errors="ignore")
    streams = []
    for match in re.finditer(r"stream\r?\n(.*?)endstream", raw, re.S):
        encoded = match.group(1).encode("latin1")
        try:
            decoded = base64.a85decode(encoded, adobe=True)
            text = zlib.decompress(decoded).decode("latin1", errors="ignore")
        except Exception:
            continue
        streams.append(text)
    return streams


def pdf_page_count(pdf_path: Path) -> int | None:
    raw = pdf_path.read_bytes().decode("latin1", errors="ignore")
    match = re.search(r"/Count\s+(\d+)", raw)
    return int(match.group(1)) if match else None


def unescape_pdf_text(value: str) -> str:
    replacements = {
        r"\(" : "(",
        r"\)" : ")",
        r"\n" : "\n",
        r"\r" : "\r",
        r"\t" : "\t",
        r"\\" : "\\",
        r"\222": "'",
        r"\226": "-",
        r"\227": "-",
        r"\262": "^2",
        r"\256": "->",
    }
    for source, target in replacements.items():
        value = value.replace(source, target)
    return value


def stream_to_text(stream: str) -> str:
    # Collect literal text from ReportLab drawing commands and preserve T* as
    # line breaks so sections remain readable after extraction.
    parts: list[str] = []
    i = 0
    while i < len(stream):
        ch = stream[i]
        if ch == "(":
            depth = 1
            i += 1
            buf = []
            while i < len(stream) and depth > 0:
                ch = stream[i]
                if ch == "\\" and i + 1 < len(stream):
                    buf.append(ch)
                    buf.append(stream[i + 1])
                    i += 2
                    continue
                if ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                if depth > 0:
                    buf.append(ch)
                i += 1
            parts.append(unescape_pdf_text("".join(buf)))
            continue
        if stream.startswith("T*", i):
            parts.append("\n")
            i += 2
            continue
        i += 1

    text = "".join(parts)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    return text.strip()


def extract_lessons(pdf_name: str, start_lesson_id: int) -> tuple[list[dict], dict]:
    pdf_path = PDF_DIR / pdf_name
    streams = decode_streams(pdf_path)
    pages = pdf_page_count(pdf_path)
    lessons = []
    for offset, stream in enumerate(streams[:pages], start=0):
        lesson_id = start_lesson_id + offset
        lesson_text = stream_to_text(stream)
        title_match = re.search(rf"Lesson {lesson_id}: ([^\n]+)", lesson_text)
        title = title_match.group(1).strip() if title_match else f"Lesson {lesson_id}"
        lessons.append(
            {
                "lesson_id": lesson_id,
                "pdf_file": pdf_name,
                "pdf_page": offset + 1,
                "title": title,
                "raw_text": lesson_text,
            }
        )

    mapping = {
        "pdf_file": pdf_name,
        "page_count": pages,
        "lesson_ids": [lesson["lesson_id"] for lesson in lessons],
        "titles": [lesson["title"] for lesson in lessons],
    }
    return lessons, mapping


def extract_analogy_reference() -> dict:
    pdf_path = PDF_DIR / ANALOGY_PDF
    streams = decode_streams(pdf_path)
    pages = pdf_page_count(pdf_path)
    return {
        "pdf_file": ANALOGY_PDF,
        "page_count": pages,
        "pages": [
            {
                "page": index + 1,
                "text": stream_to_text(stream),
            }
            for index, stream in enumerate(streams[:pages])
        ],
    }


def write_outputs() -> None:
    raw_dir = OUT_DIR / "raw_lessons"
    reference_dir = META_DIR / "references"
    raw_dir.mkdir(parents=True, exist_ok=True)
    META_DIR.mkdir(parents=True, exist_ok=True)
    reference_dir.mkdir(parents=True, exist_ok=True)

    all_lessons = []
    inventory = []
    for batch_index, pdf_name in enumerate(PDF_ORDER):
        start_lesson_id = batch_index * 5 + 1
        lessons, mapping = extract_lessons(pdf_name, start_lesson_id)
        inventory.append(mapping)
        all_lessons.extend(lessons)
        batch_file = raw_dir / f"lessons_{start_lesson_id}_{start_lesson_id + 4}.json"
        batch_file.write_text(json.dumps(lessons, indent=2), encoding="utf-8")

    inventory_file = META_DIR / "source_inventory.json"
    inventory_file.write_text(json.dumps(inventory, indent=2), encoding="utf-8")

    analogy_reference = extract_analogy_reference()
    analogy_file = reference_dir / "analogy_master.json"
    analogy_file.write_text(json.dumps(analogy_reference, indent=2), encoding="utf-8")

    lesson_index_lines = [
        "# QCML Source Inventory",
        "",
        "| Lesson ID | Title | Source PDF | Page |",
        "| --- | --- | --- | --- |",
    ]
    for lesson in all_lessons:
        lesson_index_lines.append(
            f"| {lesson['lesson_id']} | {lesson['title']} | "
            f"{lesson['pdf_file']} | {lesson['pdf_page']} |"
        )
    (META_DIR / "lesson_index.md").write_text(
        "\n".join(lesson_index_lines) + "\n", encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract QCML lesson text from PDFs.")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write extracted lesson outputs under artifacts/ and source-context metadata under _metadata/.",
    )
    args = parser.parse_args()

    if args.write:
        write_outputs()
        return

    for batch_index, pdf_name in enumerate(PDF_ORDER):
        start_lesson_id = batch_index * 5 + 1
        lessons, _ = extract_lessons(pdf_name, start_lesson_id)
        print(f"{pdf_name}: {len(lessons)} lessons")
        for lesson in lessons:
            print(f"  {lesson['lesson_id']:>2}: {lesson['title']}")


if __name__ == "__main__":
    main()
